[msg SHOP_STOP_JUNPEI [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 12 1 1]Dude, hurry up![n][f 0 4][e]

[msg JUNPEI_STOP_BURGER [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, this place is so bad for you,[n]but sometimes I just get a craving.[n][f 0 4][e]
[f 0 8 65278][f 1 31]...Hey, what about Paulownia Mall?[n][f 0 4][e]

[msg BURGER_TEIKYU]
[f 0 8 65278][f 1 31]> Wild-duck Burger...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg BURGER_ANNOUNCE]
[f 0 8 65278][f 1 31]> Wild-duck Burger...[n][f 0 4][e]

[msg BURGER_HAIRU [Menu]]
[f 0 8 65278][f 1 31]"Mystery Burger - 500 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"The ingredients are a secret!"[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15] [n]> You need a little bit of Courage to[n]eat here.[n][f 0 4][e]

[msg BURGER_HAIRU02]
[f 0 8 65278][f 1 31]> Will you stay here until it gets[n]dark?[n][f 0 4][e]

[msg JUNPEI_STOP_RESTAURANT [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Oh yeah, we better eat before we go to[n]the police station, huh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]...Wait a minute! That's not as[n]important![n][f 0 4][e]

[msg WASHOKU_ANNOUNCE]
[f 0 8 65278][f 1 31]> Wakatsu Restaurant...[n][f 0 4][e]

[msg WASHOKU_HAIRU [Menu]]
[f 0 8 65278][f 1 31]"Prodigy Platter - 680 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"Get smarter while you digest!"[n][f 0 4][e]

[msg WASHOKU_HAIRU02]
[f 0 8 65278][f 1 31]> Will you stay here until it gets[n]dark?[n][f 0 4][e]

[msg WASHOKU_TEIKYU]
[f 0 8 65278][f 1 31]> Wakatsu Restaurant...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg JUNPEI_STOP_RAMEN [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]I heard the ramen here kicks ass.[n]Wanna try it?[n][f 0 4][e]
[f 0 8 65278][f 1 31]...Hang on. We gotta get to Paulownia[n]Mall since Akihiko-senpai is waiting.[n][f 0 4][e]

[msg RAMEN_ANNOUNCE]
[f 0 8 65278][f 1 31]> Ramen shop "Hagakure"...[n][f 0 4][e]

[msg RAMEN_HAIRU [Menu]]
[f 0 8 65278][f 1 31]"Tuna - 900 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"The collagen will make your skin[n]beautiful!"[n][f 0 4][e]

[msg RAMEN_HAIRU02]
[f 0 8 65278][f 1 31]> Will you stay here until it gets[n]dark?[n][f 0 4][e]

[msg RAMEN_TEIKYU]
[f 0 8 65278][f 1 31]> Ramen shop "Hagakure"...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg GAKURYOKU_MAX_NG]
[f 0 8 65278][f 1 31]> You don't need to increase your[n]Academics.[n][f 0 4][e]

[msg JUNPEI_STOP_TAKOYAKI [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1][f 1 28 8 0 10 65535 10]Damn, that smells good. I wanna go[n]buy some, right now![n][f 0 4][e]
[f 0 8 65278][f 1 31]...But I'm not falling for it! Not[n]even delicious takoyaki can stop us[n]from getting to the police station![n][f 0 4][e]

[msg TAKOYAKI_SHONITI [Takoyaki Cook]]
[f 0 8 65278][f 1 31]Hey, you there! Come on over![n][f 0 4][e]
[f 0 8 65278][f 1 31]My takoyaki is deee-licious, and[n]only 400 yen![n][f 0 4][e]
[f 0 8 65278][f 1 31]There's no octopus in it, but...[n]Try some anyway![n][f 0 4][e]

[msg TAKOYAKI_SENTAKU]
[f 0 8 65278][f 1 31]> Will you buy the takoyaki?[n][f 0 4][e]

[sel TAKOYAKI_SEL top]
[f 0 8 65278][f 1 31]Buy[e]
[f 0 8 65278][f 1 31]Don't buy[e]

[msg TAKOYAKI_OWARI [Takoyaki Cook]]
[f 0 8 65278][f 1 31]Thanks! Come again![n][f 0 4][e]
[f 0 8 65278][f 1 31]> Obtained [f 0 25 0]![n][f 1 17][e]

[msg TAKOYAKI_KAWANAI [Takoyaki Cook]]
[f 0 8 65278][f 1 31]Oh... I see...[n][f 0 4][e]