[sel YESNO_SEL top]
[f 0 8 65278][f 1 31]Yes[e]
[f 0 8 65278][f 1 31]No[e]

[sel INTO_SEL top]
[f 0 8 65278][f 1 31]Enter[e]
[f 0 8 65278][f 1 31]Don't enter[e]

[msg STOP_UFO_CATCHER]
[f 0 8 65278][f 1 31]> It seems like the electricity is out.[n][f 0 4][e]

[msg SHOP_STOP_YUKARI [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]What are you doing?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Let's go.[n][f 0 4][e]

[msg SHOP_STOP_AEGIS [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]We have no time to spare.[n][f 0 4][e]
[f 0 8 65278][f 1 31]We must prepare ourselves quickly.[n][f 0 4][e]

[msg SHOP_STOP_SANADA [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]What are you doing?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Hurry up and get ready.[n][f 0 4][e]

[msg SHOP_STOP_ARAGAKI [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]What are you waiting for?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Hurry up.[n][f 0 4][e]

[msg SHOP_STOP_AMADA [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]There's no time.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Let's go.[n][f 0 4][e]

[msg STOP_INTO_SHOP]
[f 0 8 65278][f 1 31]> There is nothing for you to do[n]here.[n][f 0 4][e]

[msg INTO_POLICEBOX_OK]
[f 0 8 65278][f 1 31]> This seems to be the police station.[n][f 0 4][e]

[msg POLICEMAN_NOT_HERE]
[f 0 8 65278][f 1 31]> No one is here; Officer Kurosawa[n]must be on patrol...[n][f 0 4][e]

[msg JUNPEI_STOP_DRUGSTORE [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Let's go to the police station first,[n]man...[n][f 0 4][e]

[msg JUNPEI_COMMENT_ACCESSORY [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude! The police station's next door![n][f 0 4][e]

[msg ACCESSORY_SHOP_CLOSE]
[f 0 8 65278][f 1 31]> The lights are off.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's closed.[n][f 0 4][e]

[msg JIKANTUBUSI_TUTO]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]Here, you can spend time in shops[n]such as these.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Depending on where you go, you may[n]be able to raise your Charm, Courage,[n]or Academics.[n][f 0 4][e]
[f 0 8 65278][f 1 31]If these stats are high enough,[n]then you may even be able to make[n]new acquaintances.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Beyond that, you can also raise your[n]Persona's stats at the arcade.[n][e]

[msg RYOU_KAERU]
[f 0 8 65278][f 1 31]> It's getting late.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You decide to go back to the dorm.[n][f 0 4][e]

[msg RYOU_KAERU_SINYA]
[f 0 8 65278][f 1 31]> It's getting late.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You decide to go back to the dorm.[n][f 0 4][e]

[msg JUNPEI_STOP_COFFEE [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]You wanna have a cup of tea?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Well, too bad! We gotta go to the[n]police station![n][f 0 4][e]

[msg COFFEE_ANNOUNCE]
[f 0 8 65278][f 1 31]> Chagall Cafe...[n][f 0 4][e]

[msg COFFEE_MENU [Menu]]
[f 0 8 65278][f 1 31]"Pheromone Coffee - 500 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"A charming flavor that will turn on[n]your charm."[n][f 0 4][e]

[msg MIRYOKU_MAX_NG]
[f 0 8 65278][f 1 31]> It seems your Charm may not get any[n]higher.[n][f 0 4][e]

[msg HAIRU_YORU]
[f 0 8 65278][f 1 31]> Will you stay here until it gets[n]dark?[n][f 0 4][e]

[msg HAIRU_SINYA]
[f 0 8 65278][f 1 31]> Will you stay here until midnight?[n][f 0 4][e]

[msg COFFEE_NG]
[f 0 8 65278][f 1 31]> Chagall Cafe...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> They seem to be cleaning up.[n][f 0 4][e]

[msg COFFEE_TEIKYU]
[f 0 8 65278][f 1 31]> Chagall Cafe...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg JUNPEI_STOP_CD [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]We can come back later, right?[n]Let's go to the police station first.[n][f 0 4][e]

[msg CDSHOP_SETUMEI]
[f 0 8 65278][f 1 31]> Power Records...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> The store sells a variety of music.[n][f 0 4][e]

[msg JUNPEI_STOP_GAME [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Alright, alright! But, after the[n]police station, okay!?[n][f 0 4][e]

[msg GAMEC_SETUMEI]
[f 0 8 65278][f 1 31]> Game Panic...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Various arcade games are inside.[n][f 0 4][e]

[msg GAMEC_CHOICE]
[f 0 8 65278][f 1 31]> Right now, the games available[n]to play are...[n][f 0 4][e]

[sel GAMEC_CHOICE_SEL01 top]
[f 0 8 65278][f 1 31]Print Club - 1,500 yen[e]
[f 0 8 65278][f 1 31]Punching Bag - 2,000 yen[e]
[f 0 8 65278][f 1 31]Leave[e]

[sel GAMEC_CHOICE_SEL02 top]
[f 0 8 65278][f 1 31]Horror House - 3,000 yen[e]
[f 0 8 65278][f 1 31]Mole Whackers - 2,000 yen[e]
[f 0 8 65278][f 1 31]Leave[e]

[sel GAMEC_CHOICE_SEL03 top]
[f 0 8 65278][f 1 31]Quiz Game - 3,000 yen[e]
[f 0 8 65278][f 1 31]Lucky Fortune - 2,000 yen[e]
[f 0 8 65278][f 1 31]Leave[e]

[sel GAMEC_CHOICE_SEL04 top]
[f 0 8 65278][f 1 31]Punching Bag - 2,000 yen[e]
[f 0 8 65278][f 1 31]Mole Whackers - 2,000 yen[e]
[f 0 8 65278][f 1 31]Lucky Fortune - 2,000 yen[e]
[f 0 8 65278][f 1 31]Leave[e]

[msg GAMEC_END_01]
[f 0 8 65278][f 1 31]> You tested your mastery of trivia[n]against players from all over Japan...[n][f 0 4][e]

[msg GAKURYOKU_UP]
[f 0 8 65278][f 1 31]> Your Academics have increased![n][f 0 4][e]

[msg PARAM_RANK_UP_GAKURYOKU]
[f 0 8 65278][f 1 31]> Your Academics changed from[n]"[f 0 3 0]" to "[f 0 3 1]"![n][f 0 4][e]

[msg GAMEC_END_02]
[f 0 8 65278][f 1 31]> You showed the machine what you[n]could dish out.[n][f 0 4][e]

[msg TIKARA_UP]
[f 0 8 65278][f 1 31]> Your Persona's Strength has[n]increased![n][f 0 4][e]

[msg GAMEC_END_03]
[f 0 8 65278][f 1 31]> You whacked as many of the wily[n]moles as you could...[n][f 0 4][e]

[msg SOKU_UP]
[f 0 8 65278][f 1 31]> Your Persona's Speed has[n]increased![n][f 0 4][e]

[msg GAMEC_END_04]
[f 0 8 65278][f 1 31]> Dr. Edgar's macabre fortune nearly[n]came true...[n][f 0 4][e]

[msg MARYOKU_UP]
[f 0 8 65278][f 1 31]> Your Persona's Magic has[n]increased![n][f 0 4][e]

[msg GAMEC_END_05]
[f 0 8 65278][f 1 31]> You watched a scary video in the[n]small, enclosed booth...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You were alone inside, but it[n]somehow felt like there was someone[n]else with you...[n][f 0 4][e]

[msg GAMEC_END_06]
[f 0 8 65278][f 1 31]> Your photo came out fantastically![n][f 0 4][e]
[f 0 8 65278][f 1 31]> You tried out different poses and[n]graphics...[n][f 0 4][e]

[msg MIRYOKU_UP]
[f 0 8 65278][f 1 31]> Your Charm has increased.[n][f 0 4][e]

[msg PARAM_RANK_UP_MIRYOKU]
[f 0 8 65278][f 1 31]> Your Charm changed from[n]"[f 0 3 0]" to "[f 0 3 1]"![n][f 0 4][e]

[msg PARAM_MAX_SUMI]
[f 0 8 65278][f 1 31]> But it seems that statistic[n]can't go any higher...[n][f 0 4][e]

[msg UFO_CATHER]
[f 0 8 65278][f 1 31]> It's a crane game.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> One of the prizes is a [f 0 29 4092].[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It costs 200 yen to play. Will you[n]give it a try?[n][f 0 4][e]

[msg UFO_CATHER_02]
[f 0 8 65278][f 1 31]> It's a crane game.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> One of the prizes is a [f 0 29 4095].[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It costs 200 yen to play. Will you[n]give it a try?[n][f 0 4][e]

[msg UFO_CATHER_CONTINUE]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]

[msg UFO_CATHER_GET]
[f 0 8 65278][f 1 31]> You won![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 16 4092 1]> Obtained [f 0 29 4092]![n][f 0 4][e]

[msg UFO_CATHER_GET_02]
[f 0 8 65278][f 1 31]> You won![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 16 4095 1]> Obtained [f 0 29 4095]![n][f 0 4][e]

[msg UFO_CATHER_NG]
[f 0 8 65278][f 1 31]> The crane grabbed nothing but air.[n][f 0 4][e]

[msg JUNPEI_STOP_KARAOKE [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, we can check it out AFTER[n]we go to the police station.[n][f 0 4][e]
[f 0 8 65278][f 1 31]But, there's no way I'm doing a duet[n]with you![n][f 0 4][e]

[msg KARAOKE_ANNOUNCE]
[f 0 8 65278][f 1 31]> Mandragora...[n][f 0 4][e]

[msg KARAOKE_MENU [Menu]]
[f 0 8 65278][f 1 31]"Karaoke Solo - 800 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"Don't be shy... Belt it out!"[n][f 0 4][e]

[msg KARAOKE_CONTINUE]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]

[msg KARAOKE_END]
[f 0 8 65278][f 1 31]> You sang for hours and hours.[n][f 0 4][e]

[msg YUUKI_UP]
[f 0 8 65278][f 1 31]> Your Courage has increased.[n][f 0 4][e]

[msg YUUKI_MAX_NG]
[f 0 8 65278][f 1 31]> It seems your Courage may not get[n]any higher.[n][f 0 4][e]

[msg PARAM_RANK_UP_YUUKI]
[f 0 8 65278][f 1 31]> Your Courage has changed from[n][f 0 3 0] to [f 0 3 1]![n][f 0 4][e]

[msg KARAOKE_NG]
[f 0 8 65278][f 1 31]> The worker seems really busy.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15]Worker[n]I'm terribly sorry, but we're full at[n]the moment.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Weekends are always like this,[n]so you may want to try some other[n]time.[n][f 0 4][e]

[msg JUNPEI_COMMENT_ANTIQUE [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Oh, it's not open, huh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]...Wait a minute! This isn't the[n]police station![n][f 0 4][e]

[msg KOTTOU_NG]
[f 0 8 65278][f 1 31]> It's an antique store.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> However, it seems to be closed.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> The sign says it will reopen on[n]June 9th.[n][f 0 4][e]