[sel MSG_NPC000_SEL1 top]
[f 0 8 65278][f 1 31]Rose Bouquet[e]
[f 0 8 65278][f 1 31]Red Pine Bonsai[e]
[f 0 8 65278][f 1 31]Look at the other flowers[e]
[f 0 8 65278][f 1 31]Never mind[e]

[sel MSG_NPC000_SEL2 top]
[f 0 8 65278][f 1 31]Mini Cactus[e]
[f 0 8 65278][f 1 31]Glass Vase[e]
[f 0 8 65278][f 1 31]Look at the other flowers[e]
[f 0 8 65278][f 1 31]Never mind[e]

[msg MSG_NPC000_FST [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Welcome to Rafflesia.[n][f 0 4][e]
[f 0 8 65278][f 1 31]What kind of flowers are you[n]looking for today?[n][f 0 4][e]

[msg MSG_NPC000_FST2 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Would you like another type[n]of flower?[n][f 0 4][e]

[msg MSG_NPC000_FLOWER1 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]It'll be 2,000 yen for[n][f 0 25 0].[n][f 0 4][e]

[msg MSG_NPC000_FLOWER2 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]It'll be 3,000 yen for[n][f 0 25 0].[n][f 0 4][e]

[msg MSG_NPC000_FLOWER3 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]It'll be 4,000 yen for[n][f 0 25 0].[n][f 0 4][e]

[msg MSG_NPC000_FLOWER4 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]It'll be 5,000 yen for[n][f 0 25 0].[n][f 0 4][e]

[sel MSG_NPC000_YESNO top]
[f 0 8 65278][f 1 31]"Sure."[e]
[f 0 8 65278][f 1 31]"On second thought..."[e]

[msg MSG_NPC000_THANKS [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Thank you very much for[n]your purchase.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Obtained [f 0 25 0].[n][f 1 17][e]

[msg MSG_NPC000_BYE [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Please come again.[n][f 0 4][e]

[msg MSG_NPC000_DONTHAVE [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Hmm? You don't have enough space[n]for [f 0 25 0].[n][f 0 4][e]
[f 0 8 65278][f 1 31]Come back once you've organized[n]your belongings.[n][f 0 4][e]

[msg MSG_NPC000_NOMONEY [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Hmm? You don't have enough money.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Save up, and come back again.[n][f 0 4][e]

[msg JUNPEI_STOP_THEATER [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, that's NOT the police station...[n][f 0 4][e]

[msg MOVIE_TEIKYU]
[f 0 8 65278][f 1 31]> Screen Shot Movie Theater...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Tickets are sold out.[n][f 0 4][e]

[msg MOVIE_THEATER]
[f 0 8 65278][f 1 31]> Screen Shot Movie Theater...[n][f 0 4][e]

[msg MOVIE_PROGRAM_01]
[f 0 8 65278][f 1 31]> A movie marathon is playing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "For those of you who want to be[n]more charming, two French films are[n]being shown."[n][f 0 4][e]

[msg MOVIE_PROGRAM_02]
[f 0 8 65278][f 1 31]> A movie marathon is playing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "For those of you who want to be[n]more courageous, three heroic tales[n]are being shown."[n][f 0 4][e]

[msg MOVIE_PROGRAM_03]
[f 0 8 65278][f 1 31]> A movie marathon is playing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "For those of you who want to be[n]more charming, check out these epic[n]tales of love."[n][f 0 4][e]

[msg MOVIE_PROGRAM_04]
[f 0 8 65278][f 1 31]> A movie marathon is playing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "Are you brave enough to endure[n]these tales of terror?"[n][f 0 4][e]

[msg MOVIE_PROGRAM_CONTINUE]
[f 0 8 65278][f 1 31]> A student ticket is 1500 yen.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Would you like to stay and watch[n]some movies?[n][f 0 4][e]

[msg MOVIE_CONTINUE]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]

[msg MOVIE_END_01]
[f 0 8 65278][f 1 31]> You have learned some romantic[n]one-liners.[n][f 0 4][e]

[msg MOVIE_END_02]
[f 0 8 65278][f 1 31]> You've been inspired to be more[n]courageous.[n][f 0 4][e]

[msg MOVIE_END_03]
[f 0 8 65278][f 1 31]> You've learned some new ways to[n]catch a girl's eye.[n][f 0 4][e]

[msg MOVIE_END_04]
[f 0 8 65278][f 1 31]> You almost screamed, but you held[n]it in.[n][f 0 4][e]