[sel Yes_No top]
[f 0 8 65278][f 1 31]Yes[e]
[f 0 8 65278][f 1 31]No[e]

[msg GOD_OF_HARVESTS]
[f 0 8 65278][f 1 31]> It's some Inari Sushi.[n][f 0 4][e]

[msg JUNPEI_STOP_INARI [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 2 1]Damn, these look good![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 5 1 9 1]I'm not gonna eat 'em, of course.[n]I know better than to mess with[n]sacrificial offerings.[n][f 0 4][e]

[msg DONT_GET_SUSHI]
[f 0 8 65278][f 1 31]> You can't just steal someone else's[n]food.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Perhaps if your Academics were[n]higher, you could think of another[n]solution.[n][f 0 4][e]

[msg GET_SUSHI_1]
[f 0 8 65278][f 1 31]> Despite your Academic prowess, you[n]are unable to think of an acceptable[n]way to obtain it.[n][f 0 4][e]

[msg GET_SUSHI_2 [Old Lady's Voice]]
[f 0 8 65278][f 1 31]Hey![n][f 0 4][e]
[f 0 8 65278][f 1 31]You there![n][f 0 4][e]

[msg GET_SUSHI_3 [Old Lady]]
[f 0 8 65278][f 1 31]Why do you have such a sullen look on[n]your face?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Did something happen?[n][f 0 4][e]
[f 0 8 65278][f 1 31]A boy your age should be carefree...[n][f 0 4][e]
[f 0 8 65278][f 1 31]What you need is a good meal and some[n]rest, and you'll feel better![n][f 0 4][e]
[f 0 8 65278][f 1 31]Here, have this Inari Sushi...[n][f 0 4][e]

[msg GET_SUSHI]
[f 0 8 65278][f 1 31]> Obtained [f 0 25 0].[n][f 0 4][e]

[msg GET_SUSHI_4 [Old Lady]]
[f 0 8 65278][f 1 31]You have to be optimistic! Your[n]generation is Japan's future![n][f 0 4][e]
[f 0 8 65278][f 1 31]Well, good luck.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Cheer up![n][f 0 4][e]

[msg INARI_TUTO]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]Anything could happen when you join[n]your hands and wish in front of the[n]small shrine... Time will pass as[n]you fervently wish.[n][f 0 4][e]

[msg INARI_TUTO_CONT]
[f 0 8 65278][f 1 31]> Join your hands?[n][f 0 4][e]

[sel INARI_SEL top]
[f 0 8 65278][f 1 31]Yes[e]
[f 0 8 65278][f 1 31]Recall how it works[e]
[f 0 8 65278][f 1 31]No[e]

[msg MSG_INARI_CONT]
[f 0 8 65278][f 1 31]>...[n][f 0 4][e]
[f 0 8 65278][f 1 31]>......[n][f 0 4][e]
[f 0 8 65278][f 1 31]>.........[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You sensed something...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15]Mysterious Voice[n]Yip yip![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15] [n]> A voice echoed triumphantly...[n][f 0 4][e]

[msg INARI_EXP_UP]
[f 0 8 65278][f 1 31]> ...You felt your battle tactics[n]improve![n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]The amount of EXP earned today[n]will increase dramatically![n][f 0 4][e]

[msg INARI_MONEY_UP]
[f 0 8 65278][f 1 31]> ...You have a vivid image of[n]piles of cash![n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Money earned from Shuffle Time today[n]will increase dramatically![n][f 0 4][e]

[msg INARI_STAMINA_UP]
[f 0 8 65278][f 1 31]> ...You felt your spirits rise![n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]You won't get tired as easily today![n][f 0 4][e]

[msg INARI_DROPITEM_UP]
[f 0 8 65278][f 1 31]> ...You feel a little sneakier![n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]The enemy will drop more items than[n]usual today![n][f 0 4][e]

[msg INARI_GATTAI_JIKO_UP]
[f 0 8 65278][f 1 31]> ...You feel a new theory pop into[n]your head![n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]The chance of fusion accidents[n]will be greater than usual today![n][f 0 4][e]

[msg INARI_YUKARI_UP]
[f 0 8 65278][f 1 31]> Yukari's face suddenly entered[n]your mind...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Yukari's status has increased![n][f 0 4][e]

[msg INARI_JUNPEI_UP]
[f 0 8 65278][f 1 31]> Junpei's face suddenly entered[n]your mind...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Junpei's status has increased![n][f 0 4][e]

[msg INARI_SANADA_UP]
[f 0 8 65278][f 1 31]> Akihiko's face suddenly entered[n]your mind...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Akihiko's status has increased![n][f 0 4][e]

[msg INARI_MITURU_UP]
[f 0 8 65278][f 1 31]> Mitsuru's face suddenly entered[n]your mind...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Mitsuru's status has increased![n][f 0 4][e]

[msg INARI_AEGIS__UP]
[f 0 8 65278][f 1 31]> Aigis' face suddenly entered[n]your mind...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Aigis' status has increased![n][f 0 4][e]

[msg INARI_KOROMA_UP]
[f 0 8 65278][f 1 31]> Koromaru's face suddenly entered[n]your mind...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Koromaru's status has increased![n][f 0 4][e]

[msg INARI_AMADA__UP]
[f 0 8 65278][f 1 31]> Ken's face suddenly entered[n]your mind...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Ken's status has increased![n][f 0 4][e]

[msg INARI_ARAGAK_UP]
[f 0 8 65278][f 1 31]> Shinjiro's face suddenly entered[n]your mind...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Shinjiro's status has increased![n][f 0 4][e]

[msg INARI_ITEMCHANGE_01]
[f 0 8 65278][f 1 31][f 1 16 4007 1]> [f 0 29 4014] x5 converted[n]to [f 0 29 4007]![n][f 0 4][e]

[msg INARI_ITEMCHANGE_02]
[f 0 8 65278][f 1 31][f 1 16 4106 5]> [f 0 29 4094] x2 converted[n]to [f 0 29 4106] x5![n][f 0 4][e]

[msg INARI_ITEMCHANGE_03]
[f 0 8 65278][f 1 31][f 1 16 4034 1]> [f 0 29 4041] x2 converted[n]to [f 0 29 4034]![n][f 0 4][e]

[msg INARI_ITEMCHANGE_04]
[f 0 8 65278][f 1 31][f 1 16 4017 1]> [f 0 29 4114] x3 converted[n]to [f 0 29 4017]![n][f 0 4][e]

[msg INARI_ITEMCHANGE_05]
[f 0 8 65278][f 1 31][f 1 16 4004 10]> [f 0 29 4001] x20 converted[n]to [f 0 29 4004] x10![n][f 0 4][e]

[msg INARI_SHOJIMONEY_UP1]
[f 0 8 65278][f 1 31]> Your wallet feels heavier...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]You have more money![n][f 0 4][e]

[msg INARI_SHOJIMONEY_UP2]
[f 0 8 65278][f 1 31]> Your wallet feels heavier...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Your money has doubled![n][f 0 4][e]

[msg INARI_SHOJIMONEY_UP3]
[f 0 8 65278][f 1 31]> Your wallet feels heavier...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> [f 0 2 1]Your money has tripled![n][f 0 4][e]

[msg OMIKUJI_NOTYET]
[f 0 8 65278][f 1 31]> The fortune box is under[n]repairs.[n][f 0 4][e]

[msg OMIKUJI_START]
[f 0 8 65278][f 1 31]> Relationship Fortune - 100 yen[n][f 0 4][e]

[msg OMIKUJI_TUTO]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 2]Picture someone you are tied to in a[n]Social Link, and your relationship[n]will become more intimate. If your[n]bond has been reversed, it may be[n]mended. Time will pass as you read it.[n][f 0 4][e]

[msg OMIKUJI_TUTO_CONT]
[f 0 8 65278][f 1 31]> Would you like to draw one?[n][f 0 4][e]

[sel OMIKUJI_SEL top]
[f 0 8 65278][f 1 31]Yes[e]
[f 0 8 65278][f 1 31]Recall how it works[e]
[f 0 8 65278][f 1 31]No[e]

[msg OMIKUJI_COMMU_CHOOSE]
[f 0 8 65278][f 1 31]> Which Social Link will you imagine?[n][f 0 4][e]

[sel OMIKUJI_COMMUSEL_1 top]
[f 0 8 65278][f 1 31]Female classmate[e]
[f 0 8 65278][f 1 31]Male classmate[e]
[f 0 8 65278][f 1 31]Someone outside of school[e]
[f 0 8 65278][f 1 31]Cancel[e]

[sel OMIKUJI_COMMUSEL_2 top]
[f 0 8 65278][f 1 31]Yukari Takeba[e]
[f 0 8 65278][f 1 31]Fuuka Yamagishi[e]
[f 0 8 65278][f 1 31]Mitsuru Kirijo[e]
[f 0 8 65278][f 1 31]Aigis[e]
[f 0 8 65278][f 1 31]Team Manager Yuko[e]
[f 0 8 65278][f 1 31]Treasurer Chihiro[e]
[f 0 8 65278][f 1 31]Cancel[e]

[sel OMIKUJI_COMMUSEL_3 top]
[f 0 8 65278][f 1 31]Yukari Takeba[e]
[f 0 8 65278][f 1 31]Fuuka Yamagishi[e]
[f 0 8 65278][f 1 31]Mitsuru Kirijo[e]
[f 0 8 65278][f 1 31]Other Social Links[e]

[sel OMIKUJI_COMMUSEL_4 top]
[f 0 8 65278][f 1 31]Aigis[e]
[f 0 8 65278][f 1 31]Team Manager Yuko[e]
[f 0 8 65278][f 1 31]Treasurer Chihiro[e]
[f 0 8 65278][f 1 31]Cancel[e]

[sel OMIKUJI_COMMUSEL_5 top]
[f 0 8 65278][f 1 31]Classmate Kenji[e]
[f 0 8 65278][f 1 31]Student Councillor Hidetoshi[e]
[f 0 8 65278][f 1 31]Track Captain Kazushi[e]
[f 0 8 65278][f 1 31]Kendo Captain Kazushi[e]
[f 0 8 65278][f 1 31]Swim Captain Kazushi[e]
[f 0 8 65278][f 1 31]Photographer Keisuke[e]
[f 0 8 65278][f 1 31]Artist Keisuke[e]
[f 0 8 65278][f 1 31]Musician Keisuke[e]
[f 0 8 65278][f 1 31]Exchange Student Bebe[e]
[f 0 8 65278][f 1 31]Cancel[e]

[sel OMIKUJI_COMMUSEL_6 top]
[f 0 8 65278][f 1 31]Classmate Kenji[e]
[f 0 8 65278][f 1 31]Student Councillor Hidetoshi[e]
[f 0 8 65278][f 1 31]Track Captain Kazushi[e]
[f 0 8 65278][f 1 31]Kendo Captain Kazushi[e]
[f 0 8 65278][f 1 31]Swim Captain Kazushi[e]
[f 0 8 65278][f 1 31]Other Social Links[e]

[sel OMIKUJI_COMMUSEL_7 top]
[f 0 8 65278][f 1 31]Photographer Keisuke[e]
[f 0 8 65278][f 1 31]Artist Keisuke[e]
[f 0 8 65278][f 1 31]Musician Keisuke[e]
[f 0 8 65278][f 1 31]Exchange Student Bebe[e]
[f 0 8 65278][f 1 31]Cancel[e]

[sel OMIKUJI_COMMUSEL_8 top]
[f 0 8 65278][f 1 31]Bookstore Old Couple[e]
[f 0 8 65278][f 1 31]Online Gamer Maya[e]
[f 0 8 65278][f 1 31]Gourmet King Nozomi[e]
[f 0 8 65278][f 1 31]Young Girl Maiko[e]
[f 0 8 65278][f 1 31]President Tanaka[e]
[f 0 8 65278][f 1 31]Old Monk Mutatsu[e]
[f 0 8 65278][f 1 31]Rival Athlete Mamoru[e]
[f 0 8 65278][f 1 31]Terminally Ill Akinari[e]
[f 0 8 65278][f 1 31]Cancel[e]

[sel OMIKUJI_COMMUSEL_9 top]
[f 0 8 65278][f 1 31]Bookstore Old Couple[e]
[f 0 8 65278][f 1 31]Online Gamer Maya[e]
[f 0 8 65278][f 1 31]Gourmet King Nozomi[e]
[f 0 8 65278][f 1 31]Other Social Links[e]

[sel OMIKUJI_COMMUSEL_10 top]
[f 0 8 65278][f 1 31]Young Girl Maiko[e]
[f 0 8 65278][f 1 31]President Tanaka[e]
[f 0 8 65278][f 1 31]Old Monk Mutatsu[e]
[f 0 8 65278][f 1 31]Other Social Links[e]

[sel OMIKUJI_COMMUSEL_12 top]
[f 0 8 65278][f 1 31]Young Girl Maiko[e]
[f 0 8 65278][f 1 31]President Tanaka[e]
[f 0 8 65278][f 1 31]Old Monk Mutatsu[e]
[f 0 8 65278][f 1 31]Cancel[e]

[sel OMIKUJI_COMMUSEL_11 top]
[f 0 8 65278][f 1 31]Rival Athlete Mamoru[e]
[f 0 8 65278][f 1 31]Terminally Ill Akinari[e]
[f 0 8 65278][f 1 31]Cancel[e]

[msg OMIKUJI_COM_NONE]
[f 0 8 65278][f 1 31]> You have no Social Links that can[n]be developed...[n][f 0 4][e]

[msg OMIKUJI_INORU]
[f 0 8 65278][f 1 31]> You drew a fortune, hoping to[n]deepen the bond between you![n][f 0 4][e]

[msg OMIKUJI_MONEY_OK]
[f 0 8 65278][f 1 31]> You drew a fortune![n][f 0 4][e]

[msg MSG_OMIKUJI_CONT]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You hear a divine message...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15]Mysterious Voice[n]Blessings to the believer...[n][f 0 4][e]

[msg MSG_OMIKUJI_CONT_TOKUSHU]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You hear a divine message...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15]Mysterious Voice[n]Hmm...[n][f 0 4][e]
[f 0 8 65278][f 1 31]The young lady seems to have something[n]to say...[n][f 0 4][e]
[f 0 8 65278][f 1 31]You should listen to her.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15] [n]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Pleading to the gods didn't help...[n][f 0 4][e]

[msg MSG_OMIKUJI_CONT_TOKUSHU_2]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You hear a divine message...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15]Mysterious Voice[n]There's nothing so odious as a[n]lovers' quarrel...[n][f 0 4][e]
[f 0 8 65278][f 1 31]But you should work it out between[n]the two of you, rather than petitioning[n]for divine assistance.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15] [n]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Pleading to the gods didn't help...[n][f 0 4][e]

[msg OMIKUJI_CONT_YUKAR]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Yukari...[n][f 0 4][e]

[msg OMIKUJI_CONT_YUKAR_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Yukari has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 26][f 1 19 1 1725]> "Lovers" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_HUUKA]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Fuuka...[n][f 0 4][e]

[msg OMIKUJI_CONT_HUUKA_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Fuuka has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 19 1 1726][f 1 26]> "Priestress" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_MITUR]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Mitsuru...[n][f 0 4][e]

[msg OMIKUJI_CONT_MITUR_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Mitsuru has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 19 1 1727][f 1 26]> "Empress" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_AEGIS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Aigis...[n][f 0 4][e]

[msg OMIKUJI_CONT_MANAG]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Yuko...[n][f 0 4][e]

[msg OMIKUJI_CONT_MANAG_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Yuko has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 19 1 1728][f 1 26]> "Strength" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_KAIKE]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Chihiro...[n][f 0 4][e]

[msg OMIKUJI_CONT_KAIKE_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Chihiro has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 26][f 1 19 1 1729]> "Justice" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_CLASS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Kenji...[n][f 0 4][e]

[msg OMIKUJI_CONT_CLASS_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Kenji has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 26][f 1 19 1 1724]> "Magician" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_SEITO]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to[n]Hidetoshi...[n][f 0 4][e]

[msg OMIKUJI_CONT_TAIIK]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Kazushi...[n][f 0 4][e]

[msg OMIKUJI_CONT_TAIIK_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Kazushi has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 26][f 1 19 1 1736]> "Chariot" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_BUNKA]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Keisuke...[n][f 0 4][e]

[msg OMIKUJI_CONT_BUNKA_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Keisuke has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 26][f 1 19 1 1737]> "Fortune" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_DOUKO]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Bebe...[n][f 0 4][e]

[msg OMIKUJI_CONT_DOUKO_RVS]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You feel that the rift between you[n]and Bebe has been healed.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 26][f 1 19 1 1730]> "Temperance" is no longer reversed.[n][f 0 4][e]

[msg OMIKUJI_CONT_HURUH]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Bunkichi[n]and Mitsuko...[n][f 0 4][e]

[msg OMIKUJI_CONT_NET__]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Maya...[n][f 0 4][e]

[msg OMIKUJI_CONT_GURUM]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Nozomi...[n][f 0 4][e]

[msg OMIKUJI_CONT_KODOM]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Maiko...[n][f 0 4][e]

[msg OMIKUJI_CONT_TANAK]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to President[n]Tanaka...[n][f 0 4][e]

[msg OMIKUJI_CONT_HAKAI]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to the[n]monk...[n][f 0 4][e]

[msg OMIKUJI_CONT_HAKAI_2]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Mutatsu...[n][f 0 4][e]

[msg OMIKUJI_CONT_ACE__]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Mamoru...[n][f 0 4][e]

[msg OMIKUJI_CONT_YOMEI]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 9 10 0]> You became much closer to Akinari...[n][f 0 4][e]

[msg OMIKUJI_END]
[f 0 8 65278][f 1 31]> You decided to return to the dorm.[n][f 0 4][e]

[msg OMIKUJI_CONTINUE]
[f 0 8 65278][f 1 31]> Today's luck is...[n][f 0 4][e]

[msg OMIKUJI_DAIKITI]
[f 0 8 65278][f 1 31]> According to the fortune, "You will[n]have very good luck,"[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "no financial worries,"[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "and great health."[n][f 0 4][e]
[f 0 8 65278][f 1 31]> There's something inside...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 16 4094 1]> Obtained [f 0 29 4094].[n][f 0 4][e]

[msg OMIKUJI_DAIKITI_2]
[f 0 8 65278][f 1 31]> ......?[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You just found 10,000 yen![n][f 0 4][e]

[msg OMIKUJI_DAIKITI_3]
[f 0 8 65278][f 1 31]> It seems like today's your lucky day![n][f 0 4][e]

[msg OMIKUJI_DAIKITI_3_CONT]
[f 0 8 65278][f 1 31]> Your condition has improved to[n]"Great."[n][f 0 4][e]

[msg OMIKUJI_CHUKITI]
[f 0 8 65278][f 1 31]> According to the fortune, "You will[n]have fair luck."[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "Money may also be in your future."[n][f 0 4][e]

[msg OMIKUJI_CHUKITI_2]
[f 0 8 65278][f 1 31]> ......?[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You just found 1,000 yen![n][f 0 4][e]

[msg OMIKUJI_SHOKITI]
[f 0 8 65278][f 1 31]> According to the fortune, "You will[n]have a little luck."[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "You will not be significantly lucky[n]or unlucky with money."[n][f 0 4][e]

[msg OMIKUJI_SHOKITI_2]
[f 0 8 65278][f 1 31]> ......?[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You just found 500 yen![n][f 0 4][e]

[msg OMIKUJI_KYO]
[f 0 8 65278][f 1 31]> According to the fortune, "You will[n]have bad luck."[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "Be careful with your money."[n][f 0 4][e]

[msg OMIKUJI_KYO_2]
[f 0 8 65278][f 1 31]> ......?[n][f 0 4][e]
[f 0 8 65278][f 1 31]> 1,000 yen just fell out of your[n]pocket and blew away![n][f 0 4][e]

[msg OMIKUJI_DAIKYO]
[f 0 8 65278][f 1 31]> According to the fortune, "You will[n]have the very worst luck."[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "You are headed towards financial[n]disaster."[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "Your health is in grave danger."[n][f 0 4][e]

[msg OMIKUJI_DAIKYO_2]
[f 0 8 65278][f 1 31]> ......?[n][f 0 4][e]
[f 0 8 65278][f 1 31]> 5,000 yen just fell out of your[n]pocket and blew away![n][f 0 4][e]

[msg OMIKUJI_KYO_NOMONEY]
[f 0 8 65278][f 1 31]> ......?[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You just realized that you've lost[n]all your money![n][f 0 4][e]

[msg OMIKUJI_DAIKYO_3]
[f 0 8 65278][f 1 31]> For some reason, you feel tired.[n][f 0 4][e]

[msg OMIKUJI_DAIKYO_3_CONT]
[f 0 8 65278][f 1 31]> Your condition has worsened to[n]"Tired."[n][f 0 4][e]

[msg OMIKUJI_MONEY_NG]
[f 0 8 65278][f 1 31]> You don't have 100 yen.[n][f 0 4][e]

[msg OMIKUJI_END_2]
[f 0 8 65278][f 1 31]> You decided to return to the dorm.[n][f 0 4][e]

[msg JUNPEI_STOP_OMIKUJI [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Huh? Your relationship fortune?[n]Shyeah, like you'd be in a[n]relationship with anybody![n][f 0 4][e]
[f 0 8 65278][f 1 31]Anyway, save it for later. We've[n]gotta get to the police station![n][f 0 4][e]

[msg SHOGATU_STOP_OMIKUJI]
[f 0 8 65278][f 1 31]> Relationship fortune - 100 yen[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ...However, they're out of tickets[n]for today...[n][f 0 4][e]

[msg OMIKUJI_TEST]
[f 0 8 65278][f 1 31]>[f 0 3 0][n][f 0 4][e]

[sel OFFERING_SEL top]
[f 0 8 65278][f 1 31]Insert 100 yen[e]
[f 0 8 65278][f 1 31]Recall how it works[e]
[f 0 8 65278][f 1 31]Do nothing[e]

[msg SAISEN_TUTO]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]By leaving money in the offertory box,[n]your Academics will increase. If you're[n]in Great condition, the increase will[n]be even higher. Time will pass.[n][f 0 4][e]

[msg MONEY_OFFERING_OK]
[f 0 8 65278][f 1 31]> It's an offertory box.[n][f 0 4][e]

[msg SAISEN_TUTO_CONT]
[f 0 8 65278][f 1 31]> Would you like to leave a donation?[n][f 0 4][e]

[msg MONEY_OFFERING_GO]
[f 0 8 65278][f 1 31]> You left a donation.[n][f 0 4][e]

[msg MONEY_OFFERING_CONT]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ............[n][f 0 4][e]

[msg MONEY_OFFERING_NG]
[f 0 8 65278][f 1 31]> You don't have enough money.[n][f 0 4][e]

[msg MONEY_OFFERING_HAZURE]
[f 0 8 65278][f 1 31]> Nothing has changed.[n][f 0 4][e]

[msg INTELLIGENCE_BASE_STOP]
[f 0 8 65278][f 1 31]> This no longer seems to be to your[n]advantage.[n][f 0 4][e]

[msg INTELLIGENCE_BASE_UP]
[f 0 8 65278][f 1 31]> Your Academics have increased![n][f 0 4][e]

[msg INTELLIGENCE_BASE_UP_ZEK]
[f 0 8 65278][f 1 31]> You're in great condition, so your[n]Academics have increased dramatically![n][f 0 4][e]

[msg INTELLIGENCE_RANK_UP]
[f 0 8 65278][f 1 31]> Your Academics changed from[n]"[f 0 3 0]" to "[f 0 3 1]"![n][f 0 4][e]

[msg MONEY_OFFERING_OVER]
[f 0 8 65278][f 1 31]> You've already visited the shrine[n]today.[n][f 0 4][e]

[msg JUNPEI_STOP_SAISEN [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Hey, I just remembered this is a[n]shrine to the God of Academics...[n][f 0 4][e]
[f 0 8 65278][f 1 31]You bet your ass I ask him to bail[n]me out almost every day! But we gotta[n]get to the police station right now.[n][f 0 4][e]

[msg SHOGATU_STOP_SAISEN [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 2 4 1]Let's get going, [f 0 11].[n][f 0 4][e]