[sel BGMHUKA_OREDER_SEL top]
[f 0 8 65278][f 1 31]Ask for an Escape Route[e]
[f 0 8 65278][f 1 31]Ask for a specific BGM[e]
[f 0 8 65278][f 1 31]Stop the music[e]
[f 0 8 65278][f 1 31]Cancel the request[e]

[sel BGMBGM_SEL top]
[f 0 8 65278][f 1 31]Persona[e]
[f 0 8 65278][f 1 31]Mainline SMT[e]
[f 0 8 65278][f 1 31]SMT Spin-Offs[e]
[f 0 8 65287][f 1 31]Pick for Me![e]

[sel P_Music top]
[f 0 8 65278][f 1 31]Persona 1[e]
[f 0 8 65278][f 1 31]Persona 2: Innocent Sin[e]
[f 0 8 65278][f 1 31]Persona 2: Eternal Punishment[e]
[f 0 8 65278][f 1 31]Persona 3[e]

[sel P_Music2 top]
[f 0 8 65278][f 1 31]Persona 4[e]
[f 0 8 65278][f 1 31]Persona Q[e]
[f 0 8 65278][f 1 31]Persona 5[e]

[sel P_Music3 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Series Selection[e]

[sel P1 top]
[f 0 8 65278][f 1 31]Track 1: SEBEC Above Ground[e]
[f 0 8 65278][f 1 31]Track 2: Kandori's Theme -Silence-[e]
[f 0 8 65278][f 1 31]Track 3: Karma palace (PSX)[e]
[f 0 8 65278][f 1 31]Track 4: Karma Palace (PSP)[e]

[sel P1_2 top]
[f 0 8 65278][f 1 31]Track 5: School Days[e]
[f 0 8 65278][f 1 31]Track 6: Let Butterflies Spread...[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]


[sel IS top]
[f 0 8 65278][f 1 31]Track 1: Club Zodiac (PSX)[e]
[f 0 8 65278][f 1 31]Track 2: Gold (PSX)[e]
[f 0 8 65278][f 1 31]Track 3: Kasugayama High (PSX)[e]
[f 0 8 65278][f 1 31]Track 4: Maya's Theme (PSX)[e]

[sel IS_2 top]
[f 0 8 65278][f 1 31]Track 5: Mt. Katatsumuri (PSX)[e]
[f 0 8 65278][f 1 31]Track 6: Club Zodiac (PSP)[e]
[f 0 8 65278][f 1 31]Track 7: Gold (PSP)[e]
[f 0 8 65278][f 1 31]Track 8: Kasugayama High (PSP)[e]

[sel IS_3 top]
[f 0 8 65278][f 1 31]Track 9: Maya's Theme (PSP)[e]
[f 0 8 65278][f 1 31]Track 10: Mt. Katatsumuri (PSP)[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel EP top]
[f 0 8 65278][f 1 31]Track 1: Abandoned Factory (PSX)[e]
[f 0 8 65278][f 1 31]Track 2: Club Zodiac (PSX)[e]
[f 0 8 65278][f 1 31]Track 3: Kasugayama High (PSX)[e]
[f 0 8 65278][f 1 31]Track 4: Mt. Katatsumuri (PSX)[e]

[sel EP_2 top]
[f 0 8 65278][f 1 31]Track 5: Abandoned Factory (PSP)[e]
[f 0 8 65278][f 1 31]Track 6: Club Zodiac (PSP)[e]
[f 0 8 65278][f 1 31]Track 7: Kasugayama High (PSP)[e]
[f 0 8 65278][f 1 31]Track 8: Mt. Katatsumuri (PSP)[e]

[sel EP_3 top]
[f 0 8 65278][f 1 31]Track 9: Shiori[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel P3 top]
[f 0 8 65278][f 1 31]Track 1: Snow Queen[e]
[f 0 8 65278][f 1 31]Track 2: Maya's Theme[e]
[f 0 8 65278][f 1 31]Track 3: Persona[e]
[f 0 8 65278][f 1 31]Track 4: Time Castle[e]

[sel P3_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel P4 top]
[f 0 8 65278][f 1 31]Track 1: Sauna[e]
[f 0 8 65278][f 1 31]Track 2: Game[e]
[f 0 8 65278][f 1 31]Track 3: Heaven[e]
[f 0 8 65278][f 1 31]Track 4: Long Way[e]

[sel P4_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel PQ top]
[f 0 8 65278][f 1 31]Track 1: Looming Danger[e]
[f 0 8 65278][f 1 31]Track 2: Maze Of Life[e]
[f 0 8 65278][f 1 31]Track 3: The Voice Someone Calls[e]

[sel PQ_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel P5 top]
[f 0 8 65278][f 1 31]Track 1: Beneath the Mask[e]
[f 0 8 65278][f 1 31]Track 2: Beneath the Mask (Inst)[e]
[f 0 8 65278][f 1 31]Track 3: Layer Cake[e]
[f 0 8 65278][f 1 31]Track 4: Life Will Change[e]

[sel P5_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel SMT_Music top]
[f 0 8 65278][f 1 31]SMT 1, 2, & if...[e]
[f 0 8 65278][f 1 31]SMT 3 & 4[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Series Selection[e]

[sel SMT1 top]
[f 0 8 65278][f 1 31]Track 1: Cathedral (SMT 1)[e]
[f 0 8 65278][f 1 31]Track 2: Disco (SMT 2)[e]
[f 0 8 65278][f 1 31]Track 3: 3D Makai (SMT 2)[e]
[f 0 8 65278][f 1 31]Track 4: City Of The Makai (if...)[e]

[sel SMT1_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel SMT3 top]
[f 0 8 65278][f 1 31]Track 1: Labyrinth of Amala (SMT 3)[e]
[f 0 8 65278][f 1 31]Track 2: Sound Test (SMT 3)[e]
[f 0 8 65278][f 1 31]Track 3: Tokyo (SMT 4)[e]
[f 0 8 65278][f 1 31]Track 4: Ikebukuro (SMT 4)[e]

[sel SMT3_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel SpinSMT_Music top]
[f 0 8 65278][f 1 31]Majin Tensei 1[e]
[f 0 8 65278][f 1 31]Majin Tensei 2[e]
[f 0 8 65278][f 1 31]Digital Devil Saga[e]
[f 0 8 65278][f 1 31]Raidou 1 & 2[e]

[sel SpinSMT_Music2 top]
[f 0 8 65278][f 1 31]Others[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Series Selection[e]

[sel MJ top]
[f 0 8 65278][f 1 31]Track 1: Flame Up Fragment[e]
[f 0 8 65278][f 1 31]Track 2: Devil Dance[e]
[f 0 8 65278][f 1 31]Track 3: Chaotic Law[e]

[sel MJ_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel MJ2 top]
[f 0 8 65278][f 1 31]Track 1: A.D. 1995 Story[e]
[f 0 8 65278][f 1 31]Track 2: Smash Up[e]
[f 0 8 65278][f 1 31]Track 3: Evolution[e]
[f 0 8 65278][f 1 31]Track 4: Assault[e]

[sel MJ2_2 top]
[f 0 8 65278][f 1 31]Track 5: Sourpuss[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel DDS top]
[f 0 8 65278][f 1 31]Track 1: Sahasrara (DDS 1)[e]
[f 0 8 65278][f 1 31]Track 2: River Of Samsara (DDS 1)[e]
[f 0 8 65278][f 1 31]Track 3: Mad Mart (DDS 2)[e]
[f 0 8 65278][f 1 31]Track 4: Egg Of The Universe (DDS 2)[e]

[sel DDS_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel Raidou top]
[f 0 8 65278][f 1 31]Track 1: Tsukudo-Cho (Raidou 1)[e]
[f 0 8 65278][f 1 31]Track 2: Go! Raidou (Raidou 1)[e]
[f 0 8 65278][f 1 31]Track 3: The Summoner... (Raidou 2)[e]
[f 0 8 65278][f 1 31]Track 4: Adventure (Raidou 2)[e]

[sel Raidou_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel Other top]
[f 0 8 65278][f 1 31]Track 1: Algon HQ (Soul Hackers 1)[e]
[f 0 8 65278][f 1 31]Track 2: Club Ezekiel (Devil Summoner)[e]
[f 0 8 65278][f 1 31]Track 3: Dragon's Belly (Jack Bros.)[e]

[sel Other_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[msg BGMHUKA_ORDER_BGM_CHANGE [Fuuka]]
[f 0 8 65278][f 1 31]Sure![n][f 0 4][e]
[f 0 8 65278][f 1 31]...Here are the series I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE2 [Fuuka]]
[f 0 8 65278][f 1 31]...Here are the games I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE3 [Fuuka]]
[f 0 8 65278][f 1 31]...Here are the songs I have.[n]Which one do you want to hear?[n][f 0 4][e]

[msg BGMPage1of1]
[f 0 8 65278][f 1 31]  Page 1 of 1.[n][f 0 21 9999][e]

[msg BGMPage1of2]
[f 0 8 65278][f 1 31]  Page 1 of 2.[n][f 0 21 9999][e]

[msg BGMPage2of2]
[f 0 8 65278][f 1 31]  Page 2 of 2.[n][f 0 21 9999][e]

[msg BGMPage1of3]
[f 0 8 65278][f 1 31]  Page 1 of 3.[n][f 0 21 9999][e]

[msg BGMPage2of3]
[f 0 8 65278][f 1 31]  Page 2 of 3.[n][f 0 21 9999][e]

[msg BGMPage3of3]
[f 0 8 65278][f 1 31]  Page 3 of 3.[n][f 0 21 9999][e]

[msg BASE_HUKA_ORDER_BGM_CHANGE_DO [Fuuka]]
[f 0 8 65278][f 1 31]There you go.[n][f 0 4][e]
[f 0 8 65278][f 1 31]If you want to listen to something[n]else, please let me know.[n][f 0 4][e]

[msg Fuuka_Tutorial]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 1]You can press Left or Right on the D-Pad to go to the[n]Previous or Next Page.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 1]You can press Select to shuffle all[n]songs in the current section.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 1]You can press Start to return to the previous section.[n][f 0 4][e]

[msg No_Music [Fuuka]]
[f 0 8 65278][f 1 31]You don't own any soundtracks.[n][f 0 4][e]
[f 0 8 65278][f 1 31]You should buy some from Power Records at the mall.[n][f 0 4][e]

[msg No_PersonaMusic [Fuuka]]
[f 0 8 65278][f 1 31]You don't own any Persona soundtracks.[n][f 0 4][e]

[msg No_SMTMusic [Fuuka]]
[f 0 8 65278][f 1 31]You don't own any SMT soundtracks.[n][f 0 4][e]

[msg No_SpinMusic [Fuuka]]
[f 0 8 65278][f 1 31]You don't own any SMT Spin-Off soundtracks.[n][f 0 4][e]

[msg sebec]
[f 0 8 65278][f 1 31]  Persona 1[n]  The Snow Queen[n][f 0 21 45][e]

[msg kandori]
[f 0 8 65278][f 1 31]  Persona 1[n]  Kandori's Theme -Silence-[n][f 0 21 45][e]

[msg karmaPSX]
[f 0 8 65278][f 1 31]  Persona 1[n]  Karma Palace (PSX)[n][f 0 21 45][e]

[msg karmaPSP]
[f 0 8 65278][f 1 31]  Persona 1[n]  Karma Palace (PSP)[n][f 0 21 45][e]

[msg school]
[f 0 8 65278][f 1 31]  Persona 1[n]  School Days[n][f 0 21 45][e]

[msg butterfly]
[f 0 8 65278][f 1 31]  Persona 1[n]  Let Butterflies Spread...[n][f 0 21 45][e]

[msg zodiacISPSX]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Club Zodiac (PSX)[n][f 0 21 45][e]

[msg goldPSX]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Gold (PSX)[n][f 0 21 45][e]

[msg kasuISPSX]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Kasugayama High (PSX)[n][f 0 21 45][e]

[msg mayaPSX]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Maya's Theme (PSX)[n][f 0 21 45][e]

[msg katatISPSX]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Mt. Katatsumuri (PSX)[n][f 0 21 45][e]

[msg zodiacISPSP]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Club Zodiac (PSP)[n][f 0 21 45][e]

[msg goldPSP]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Gold (PSP)[n][f 0 21 45][e]

[msg kasuISPSP]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Kasugayama High (PSP)[n][f 0 21 45][e]

[msg mayaPSP]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Maya's Theme (PSP)[n][f 0 21 45][e]

[msg katatISPSP]
[f 0 8 65278][f 1 31]  Persona 2: Innocent Sin[n]  Mt. Katatsumuri (PSP)[n][f 0 21 45][e]

[msg factoryPSX]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Abandoned Factory (PSX)[n][f 0 21 45][e]

[msg zodiacEPPSX]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Club Zodiac (PSX)[n][f 0 21 45][e]

[msg kasuEPPSX]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Kasugayama High (PSX)[n][f 0 21 45][e]

[msg katatEPPSX]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Mt. Katatsumuri (PSX)[n][f 0 21 45][e]

[msg factoryPSP]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Abandoned Factory (PSP)[n][f 0 21 45][e]

[msg zodiacEPPSP]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Club Zodiac (PSP)[n][f 0 21 45][e]

[msg kasuEPPSP]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Kasugayama High (PSP)[n][f 0 21 45][e]

[msg katatEPPSP]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Mt. Katatsumuri (PSP)[n][f 0 21 45][e]

[msg shiori]
[f 0 8 65278][f 1 31]  Persona 2: Eternal Punishment[n]  Shiori[n][f 0 21 45][e]

[msg sauna]
[f 0 8 65278][f 1 31]  Persona 4[n]  Sauna[n][f 0 21 45][e]

[msg game]
[f 0 8 65278][f 1 31]  Persona 4[n]  Game[n][f 0 21 45][e]

[msg heaven]
[f 0 8 65278][f 1 31]  Persona 4[n]  Heaven[n][f 0 21 45][e]

[msg longWay]
[f 0 8 65278][f 1 31]  Persona 4[n]  Long Way[n][f 0 21 45][e]

[msg beneathMask]
[f 0 8 65278][f 1 31]  Persona 5[n]  Beneath the Mask[n][f 0 21 45][e]

[msg maskInst]
[f 0 8 65278][f 1 31]  Persona 5[n]  Beneath the Mask (Inst)[n][f 0 21 45][e]

[msg cake]
[f 0 8 65278][f 1 31]  Persona 5[n]  Layer Cake[n][f 0 21 45][e]

[msg life]
[f 0 8 65278][f 1 31]  Persona 5[n]  Life Will Change[n][f 0 21 45][e]

[msg believe]
[f 0 8 65278][f 1 31]  Persona 5[n]  I Believe[n][f 0 21 45][e]

[msg danger]
[f 0 8 65278][f 1 31]  Persona Q[n]  Looming Danger[n][f 0 21 45][e]

[msg maze]
[f 0 8 65278][f 1 31]  Persona Q[n]  Maze Of Life[n][f 0 21 45][e]

[msg voice]
[f 0 8 65278][f 1 31]  Persona Q[n]  The Voice Someone Calls[n][f 0 21 45][e]

[msg cathedral]
[f 0 8 65278][f 1 31]  Shin Megami Tensei 1[n]  Cathedral[n][f 0 21 45][e]

[msg disco]
[f 0 8 65278][f 1 31]  Shin Megami Tensei 2[n]  Disco[n][f 0 21 45][e]

[msg makai]
[f 0 8 65278][f 1 31]  Shin Megami Tensei 2[n]  3D Makai[n][f 0 21 45][e]

[msg cityMakai]
[f 0 8 65278][f 1 31]  Shin Megami Tensei if...[n]  City Of The Makai[n][f 0 21 45][e]

[msg amala]
[f 0 8 65278][f 1 31]  Shin Megami Tensei 3[n]  Labyrinth of Amala[n][f 0 21 45][e]

[msg soundTest]
[f 0 8 65278][f 1 31]  Shin Megami Tensei 3[n]  Sound Test[n][f 0 21 45][e]

[msg tokyo]
[f 0 8 65278][f 1 31]  Shin Megami Tensei 4[n]  Tokyo[n][f 0 21 45][e]

[msg ikebukuro]
[f 0 8 65278][f 1 31]  Shin Megami Tensei 4[n]  Ikebukuro[n][f 0 21 45][e]

[msg flame]
[f 0 8 65278][f 1 31]  Majin Tensei 1[n]  Flame Up Fragment[n][f 0 21 45][e]

[msg devil]
[f 0 8 65278][f 1 31]  Majin Tensei 1[n]  Devil Dance[n][f 0 21 45][e]

[msg chaotic]
[f 0 8 65278][f 1 31]  Majin Tensei 1[n]  Chaotic Law[n][f 0 21 45][e]

[msg ad]
[f 0 8 65278][f 1 31]  Majin Tensei 2[n]  A.D. 1995 Story[n][f 0 21 45][e]

[msg smash]
[f 0 8 65278][f 1 31]  Majin Tensei 2[n]  Smash Up[n][f 0 21 45][e]

[msg evolution]
[f 0 8 65278][f 1 31]  Majin Tensei 2[n]  Evolution[n][f 0 21 45][e]

[msg assault]
[f 0 8 65278][f 1 31]  Majin Tensei 2[n]  Assault[n][f 0 21 45][e]

[msg sourpuss]
[f 0 8 65278][f 1 31]  Majin Tensei 2[n]  Sourpuss[n][f 0 21 45][e]

[msg sahasrara]
[f 0 8 65278][f 1 31]  Digital Devil Saga 1[n]  Sahasrara[n][f 0 21 45][e]

[msg samsara]
[f 0 8 65278][f 1 31]  Digital Devil Saga 1[n]  River Of Samsara[n][f 0 21 45][e]

[msg madMart]
[f 0 8 65278][f 1 31]  Digital Devil Saga 2[n]  Mad Mart[n][f 0 21 45][e]

[msg egg]
[f 0 8 65278][f 1 31]  Digital Devil Saga 2[n]  Egg Of The Universe[n][f 0 21 45][e]

[msg tsukudo]
[f 0 8 65278][f 1 31]  Raidou 1[n]  Tsukudo-Cho[n][f 0 21 45][e]

[msg go]
[f 0 8 65278][f 1 31]  Raidou 1[n]  Go! Raidou[n][f 0 21 45][e]

[msg tsukigata]
[f 0 8 65278][f 1 31]  Raidou 2[n]  The Summoner of Tsukigata[n][f 0 21 45][e]

[msg adventure]
[f 0 8 65278][f 1 31]  Raidou 2[n]  Adventure[n][f 0 21 45][e]

[msg algon]
[f 0 8 65278][f 1 31]  Soul Hackers 1[n]  Go! Raidou[n][f 0 21 45][e]

[msg ezekiel]
[f 0 8 65278][f 1 31]  Devil Summoner[n]  Club Ezekiel[n][f 0 21 45][e]

[msg belly]
[f 0 8 65278][f 1 31]  Jack Bros.[n]  Dragon's Belly[n][f 0 21 45][e]

[msg snow]
[f 0 8 65278][f 1 31]  Persona 3[n]  The Snow Queen[n][f 0 21 45][e]

[msg mayaP3]
[f 0 8 65278][f 1 31]  Persona 3[n]  Maya's Theme[n][f 0 21 45][e]

[msg persona]
[f 0 8 65278][f 1 31]  Persona 3[n]  Persona[n][f 0 21 45][e]

[msg castle]
[f 0 8 65278][f 1 31]  Persona 3[n]  Time Castle[n][f 0 21 45][e]