[sel BGMHUKA_OREDER_SEL top]
[f 0 8 65278][f 1 31]Ask for an Escape Route[e]
[f 0 8 65278][f 1 31]Ask for a specific BGM[e]
[f 0 8 65278][f 1 31]Stop the music[e]
[f 0 8 65278][f 1 31]Cancel the request[e]

[sel BGMBGM_SEL top]
[f 0 8 65278][f 1 31]Persona[e]
[f 0 8 65278][f 1 31]Mainline SMT[e]
[f 0 8 65278][f 1 31]SMT Spin-Offs[e]
[f 0 8 65287][f 1 31]Pick for Me![e]

[sel P_Music top]
[f 0 8 65278][f 1 31]Persona 1[e]
[f 0 8 65278][f 1 31]Persona 2: Innocent Sin[e]
[f 0 8 65278][f 1 31]Persona 2: Eternal Punishment[e]
[f 0 8 65278][f 1 31]Persona 3[e]

[sel P_Music2 top]
[f 0 8 65278][f 1 31]Persona 4[e]
[f 0 8 65278][f 1 31]Persona Q[e]
[f 0 8 65278][f 1 31]Persona 5[e]

[sel P_Music3 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Series Selection[e]

[sel P1 top]
[f 0 8 65278][f 1 31]Track 1: SEBEC Above Ground[e]
[f 0 8 65278][f 1 31]Track 2: Kandori's Theme -Silence-[e]
[f 0 8 65278][f 1 31]Track 3: Karma palace (PSX)[e]
[f 0 8 65278][f 1 31]Track 4: Karma Palace (PSP)[e]

[sel P1_2 top]
[f 0 8 65278][f 1 31]Track 5: School Days[e]
[f 0 8 65278][f 1 31]Track 6: Let Butterflies Spread...[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]


[sel IS top]
[f 0 8 65278][f 1 31]Track 1: Club Zodiac (PSX)[e]
[f 0 8 65278][f 1 31]Track 2: Gold (PSX)[e]
[f 0 8 65278][f 1 31]Track 3: Kasyugayama High (PSX)[e]
[f 0 8 65278][f 1 31]Track 4: Maya's Theme (PSX)[e]

[sel IS_2 top]
[f 0 8 65278][f 1 31]Track 5: Mt. Katatsumuri (PSX)[e]
[f 0 8 65278][f 1 31]Track 6: Club Zodiac (PSP)[e]
[f 0 8 65278][f 1 31]Track 7: Gold (PSP)[e]
[f 0 8 65278][f 1 31]Track 8: Kasugayama High (PSP)[e]

[sel IS_3 top]
[f 0 8 65278][f 1 31]Track 9: Maya's Theme (PSP)[e]
[f 0 8 65278][f 1 31]Track 10: Mt. Katatsumuri (PSP)[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel EP top]
[f 0 8 65278][f 1 31]Track 1: Abandoned Factory (PSX)[e]
[f 0 8 65278][f 1 31]Track 2: Club Zodiac (PSX)[e]
[f 0 8 65278][f 1 31]Track 3: Kasyugayama High (PSX)[e]
[f 0 8 65278][f 1 31]Track 4: Mt. Katatsumuri (PSX)[e]

[sel EP_2 top]
[f 0 8 65278][f 1 31]Track 5: Abandoned Factory (PSP)[e]
[f 0 8 65278][f 1 31]Track 6: Club Zodiac (PSP)[e]
[f 0 8 65278][f 1 31]Track 7: Kasugayama High (PSP)[e]
[f 0 8 65278][f 1 31]Track 8: Mt. Katatsumuri (PSP)[e]

[sel EP_3 top]
[f 0 8 65278][f 1 31]Track 9: Shiori[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel P3 top]
[f 0 8 65278][f 1 31]Track 1: Snow Queen[e]
[f 0 8 65278][f 1 31]Track 2: Maya's Theme[e]
[f 0 8 65278][f 1 31]Track 3: Persona[e]
[f 0 8 65278][f 1 31]Track 4: Time Castle[e]

[sel P3_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel P4 top]
[f 0 8 65278][f 1 31]Track 1: Sauna[e]
[f 0 8 65278][f 1 31]Track 2: Game[e]
[f 0 8 65278][f 1 31]Track 3: Heaven[e]
[f 0 8 65278][f 1 31]Track 4: Long Way[e]

[sel P4_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel PQ top]
[f 0 8 65278][f 1 31]Track 1: Looming Danger[e]
[f 0 8 65278][f 1 31]Track 2: Maze Of Life[e]
[f 0 8 65278][f 1 31]Track 3: The Voice Someone Calls[e]

[sel PQ_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel P5 top]
[f 0 8 65278][f 1 31]Track 1: Beneath the Mask[e]
[f 0 8 65278][f 1 31]Track 2: Beneath the Mask (Inst)[e]
[f 0 8 65278][f 1 31]Track 3: Layer Cake[e]
[f 0 8 65278][f 1 31]Track 4: Life Will Change[e]

[sel P5_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel SMT_Music top]
[f 0 8 65278][f 1 31]SMT 1, 2, & if...[e]
[f 0 8 65278][f 1 31]SMT 3 & 4[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Series Selection[e]

[sel SMT1 top]
[f 0 8 65278][f 1 31]Track 1: Cathedral (SMT 1)[e]
[f 0 8 65278][f 1 31]Track 2: Disco (SMT 2)[e]
[f 0 8 65278][f 1 31]Track 3: 3D Makai (SMT 2)[e]
[f 0 8 65278][f 1 31]Track 4: City Of The Makai (if...)[e]

[sel SMT1_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel SMT3 top]
[f 0 8 65278][f 1 31]Track 1: Labyrinth of Amala (SMT 3)[e]
[f 0 8 65278][f 1 31]Track 2: Sound Test (SMT 3)[e]
[f 0 8 65278][f 1 31]Track 3: Tokyo (SMT 4)[e]
[f 0 8 65278][f 1 31]Track 4: Ikebukuro (SMT 4)[e]

[sel SMT3_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel SpinSMT_Music top]
[f 0 8 65278][f 1 31]Majin Tensei 1[e]
[f 0 8 65278][f 1 31]Majin Tensei 2[e]
[f 0 8 65278][f 1 31]Digital Devil Saga[e]
[f 0 8 65278][f 1 31]Raidou 1 & 2[e]

[sel SpinSMT_Music2 top]
[f 0 8 65278][f 1 31]Others[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Series Selection[e]

[sel MJ top]
[f 0 8 65278][f 1 31]Track 1: Flame Up Fragment[e]
[f 0 8 65278][f 1 31]Track 2: Devil Dance[e]
[f 0 8 65278][f 1 31]Track 3: Chaotic Law[e]

[sel MJ_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel MJ2 top]
[f 0 8 65278][f 1 31]Track 1: A.D. 1995 Story[e]
[f 0 8 65278][f 1 31]Track 2: Smash Up[e]
[f 0 8 65278][f 1 31]Track 3: Evolution[e]
[f 0 8 65278][f 1 31]Track 4: Assault[e]

[sel MJ2_2 top]
[f 0 8 65278][f 1 31]Track 5: Sourpuss[e]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel DDS top]
[f 0 8 65278][f 1 31]Track 1: Sahasrara (DDS 1)[e]
[f 0 8 65278][f 1 31]Track 2: River Of Samsara (DDS 1)[e]
[f 0 8 65278][f 1 31]Track 3: Mad Mart (DDS 2)[e]
[f 0 8 65278][f 1 31]Track 4: Egg Of The Universe (DDS 2)[e]

[sel DDS_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel Raidou top]
[f 0 8 65278][f 1 31]Track 1: Tsukudo-Cho (Raidou 1)[e]
[f 0 8 65278][f 1 31]Track 2: Go! Raidou (Raidou 1)[e]
[f 0 8 65278][f 1 31]Track 3: The Summoner... (Raidou 2)[e]
[f 0 8 65278][f 1 31]Track 4: Adventure (Raidou 2)[e]

[sel Raidou_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[sel Other top]
[f 0 8 65278][f 1 31]Track 1: Algon HQ (Soul Hackers 1)[e]
[f 0 8 65278][f 1 31]Track 2: Club Ezekiel (Devil Summoner)[e]
[f 0 8 65278][f 1 31]Track 3: Dragon's Belly (Jack Bros.)[e]

[sel Other_2 top]
[f 0 8 65278][f 1 31]Pick for Me![e]
[f 0 8 65278][f 1 31]Return to Game Selection[e]

[msg BGMHUKA_ORDER_BGM_CHANGE [Fuuka]]
[f 0 8 65278][f 1 31]Sure![n][f 0 4][e]
[f 0 8 65278][f 1 31]...Here are the series I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE2 [Fuuka]]
[f 0 8 65278][f 1 31]...Here are the games I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE2_1of2 [Fuuka  (Page 1 of 2)]]
[f 0 8 65278][f 1 31]...Here are the games I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE2_2of2 [Fuuka  (Page 2 of 2)]]
[f 0 8 65278][f 1 31]...Here are the games I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE2_1of3 [Fuuka  (Page 1 of 3)]]
[f 0 8 65278][f 1 31]...Here are the games I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE2_2of3 [Fuuka  (Page 2 of 3)]]
[f 0 8 65278][f 1 31]...Here are the games I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE2_3of3 [Fuuka  (Page 3 of 3)]]
[f 0 8 65278][f 1 31]...Here are the games I have.[n]Which one do you want?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE3_1of2 [Fuuka  (Page 1 of 2)]]
[f 0 8 65278][f 1 31]...Here are the songs I have.[n]Which one do you want to hear?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE3_2of2 [Fuuka  (Page 2 of 2)]]
[f 0 8 65278][f 1 31]...Here are the songs I have.[n]Which one do you want to hear?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE3_1of3 [Fuuka  (Page 1 of 3]]
[f 0 8 65278][f 1 31]...Here are the songs I have.[n]Which one do you want to hear?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE3_2of3 [Fuuka  (Page 2 of 3]]
[f 0 8 65278][f 1 31]...Here are the songs I have.[n]Which one do you want to hear?[n][f 0 4][e]

[msg HUKA_ORDER_BGM_CHANGE3_3of3 [Fuuka  (Page 3 of 3]]
[f 0 8 65278][f 1 31]...Here are the songs I have.[n]Which one do you want to hear?[n][f 0 4][e]

[msg BASE_HUKA_ORDER_BGM_CHANGE_DO [Fuuka]]
[f 0 8 65278][f 1 31]There you go.[n][f 0 4][e]
[f 0 8 65278][f 1 31]If you want to listen to something[n]else, please let me know.[n][f 0 4][e]

[msg Fuuka_Tutorial]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 1]You can press Left or Right on the D-Pad to go to the[n]Previous or Next Page.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 1]You can press Select to shuffle all[n]songs in the current section.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 1]You can press Start to return to the previous section.[n][f 0 4][e]

[msg No_Music [Fuuka]]
[f 0 8 65278][f 1 31]You don't own any soundtracks.[n][f 0 4][e]