[sel School]
[f 0 8 -258][f 1 31]School Entranceway[e]
[f 0 8 -258][f 1 31]1st Floor, Main Lobby[e]
[f 0 8 -258][f 1 31]1st Floor, Left Hall[e]
[f 0 8 -258][f 1 31]Next Page (1/3)[e]

[sel School2]
[f 0 8 -258][f 1 31]1st Floor, Right Hall[e]
[f 0 8 -258][f 1 31]Sports Clubs[e]
[f 0 8 -258][f 1 31]Classroom 2-F[e]
[f 0 8 -258][f 1 31]Next Page (2/3)[e]

[sel School3]
[f 0 8 -258][f 1 31]2nd Floor, Hallway[e]
[f 0 8 -258][f 1 31]Rooftop[e]
[f 0 8 -258][f 1 31]Town Map[e]
[f 0 8 -258][f 1 31]Next Page (3/3)[e]

[sel DormOutside]
[f 0 5 -258][f 1 31]1st Floor, Lounge[e]
[f 0 5 -258][f 1 31]Town Map[e]

[sel Dorm]
[f 0 5 -258][f 1 31]Your Room[e]
[f 0 5 -258][f 1 31]Dorm Entrance[e]
[f 0 5 -258][f 1 31]1st Floor, Lounge[e]
[f 0 5 -258][f 1 31]Next Page (1/3)[e]

[sel Dorm2]
[f 0 5 -258][f 1 31]2nd Floor, Hallway[e]
[f 0 5 -258][f 1 31]3rd Floor, Hallway[e]
[f 0 5 -258][f 1 31]4th Floor, Hallway[e]
[f 0 5 -258][f 1 31]Next Page (2/3)[e]

[sel Dorm3]
[f 0 5 -258][f 1 31]5th Floor, Hallway[e]
[f 0 5 -258][f 1 31]Meeting Room[e]
[f 0 5 -258][f 1 31]Town Map[e]
[f 0 5 -258][f 1 31]Next Page (3/3)[e]

[sel Mall]
[f 0 8 -258][f 1 31]Paulownia Mall[e]
[f 0 8 -258][f 1 31]Back Alley[e]
[f 0 8 -258][f 1 31]Shops[e]
[f 0 8 -258][f 1 31]Town Map[e]

[sel MallFacilities]
[f 0 8 -258][f 1 31]Club Escapade[e]
[f 0 8 -258][f 1 31]Chagall Cafe[e]
[f 0 8 -258][f 1 31]Be blue V[e]
[f 0 8 -258][f 1 31]Next Page (1/3)[e]

[sel MallFacilities2]
[f 0 8 -258][f 1 31]Police Station[e]
[f 0 8 -258][f 1 31]Mandragora[e]
[f 0 8 -258][f 1 31]Shinshoudo Antiques[e]
[f 0 8 -258][f 1 31]Next Page (2/3)[e]

[sel MallFacilities3]
[f 0 8 -258][f 1 31]Aohige Pharmacy[e]
[f 0 8 -258][f 1 31]Crane Game[e]
[f 0 8 -258][f 1 31]Game Panic[e]
[f 0 8 -258][f 1 31]Next Page (3/3)[e]

[sel Iwatodai]
[f 0 8 -258][f 1 31]Iwatodai Station[e]
[f 0 8 -258][f 1 31]Iwatodai Strip Mall, Ground Floor[e]
[f 0 8 -258][f 1 31]Iwatodai Strip Mall, Upper Floors[e]
[f 0 8 -258][f 1 31]Next Page (1/2)[e]

[sel Iwatodai2]
[f 0 8 -258][f 1 31]Shops[e]
[f 0 8 -258][f 1 31]Town Map[e]
[f 0 8 -258][f 1 31]Next Page (2/2)[e]

[sel IwatodaiFacilities]
[f 0 8 -258][f 1 31]Wild-Duck Burger[e]
[f 0 8 -258][f 1 31]Wakatsu Restaurant[e]
[f 0 8 -258][f 1 31]Hagakure[e]
[f 0 8 -258][f 1 31]Beef Bowl Shop[e]

[sel PortIsland]
[f 0 8 -258][f 1 31]Port Island Station[e]
[f 0 8 -258][f 1 31]Station Outskirts[e]
[f 0 8 -258][f 1 31]Shops[e]
[f 0 8 -258][f 1 31]Town Map[e]

[sel PortFacilities]
[f 0 8 -258][f 1 31]Rafflesia[e]
[f 0 8 -258][f 1 31]Screen Shot[e]

[msg Choose]
[f 0 8 -258][f 1 31]> Where would you like to go?[e]

[msg RoomMsg]
[f 0 8 -258][f 1 31]Quick Traveling to your room will change the time of day.[n]Continue?[e]

[sel Room]
[f 0 5 -258][f 1 31]Yes[e]
[f 0 5 -258][f 1 31]No[e]

[sel DormLobby]
[f 0 5 -258][f 1 31]Yes[e]
[f 0 5 -258][f 1 31]No[e]

[msg DormLobbyMsg]
[f 0 8 -258][f 1 31]Quick Traveling into the Dorm will change the time of day.[n]Continue?[e]

[msg GOINTO_MYROOM]
[f 0 8 65278][f 1 31]> It's almost midnight...[n][f 0 4][e]

[msg HELP_GOINTO_MYROOM]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 1]If you go back into your room,[n]it will become midnight.[n][f 0 4][e]

[msg GOINTO_MYROOM_OK]
[f 0 8 65278][f 1 31]> Will you go back to your room now?[n][f 0 4][e]

[msg GOINTO_MYROOM_SAVE_OK]
[f 0 8 65278][f 1 31]> Will you go back to your room[n]for today?[n][f 0 4][e]

[msg GOINTO_MYROOM_SLEEP]
[f 0 8 65278][f 1 31]> You feel tired. You should get[n]some rest...[n][f 0 4][e]

[msg GOINTO_MYROOM_LASTWEEK]
[f 0 8 65278][f 1 31]> You feel very tired...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You should rest for today...[n][f 0 4][e]

[msg STOP_INTO_MYROOM]
[f 0 8 65278][f 1 31]> You were told to come to the[n]4th floor today...[n][f 0 4][e]

[msg STOP_INTO_MYROOM_LAST_DA]
[f 0 8 65278][f 1 31]> You must go to Tartarus...[n][f 0 4][e]

[sel INTO_ROOM_SEL top]
[f 0 8 65278][f 1 31]Go back[e]
[f 0 8 65278][f 1 31]Don't go back[e]

[msg SHOP_STOP_YUKARI [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]What are you doing?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Let's go.[n][f 0 4][e]

[msg SHOP_STOP_AEGIS [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]We have no time to spare.[n][f 0 4][e]
[f 0 8 65278][f 1 31]We must prepare ourselves quickly.[n][f 0 4][e]

[msg SHOP_STOP_SANADA [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]What are you doing?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Hurry up and get ready.[n][f 0 4][e]

[msg SHOP_STOP_ARAGAKI [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]What are you waiting for?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Hurry up.[n][f 0 4][e]

[msg SHOP_STOP_AMADA [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]There's no time.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Let's go.[n][f 0 4][e]

[msg STOP_INTO_SHOP]
[f 0 8 65278][f 1 31]> There is nothing for you to do[n]here.[n][f 0 4][e]

[msg JUNPEI_COMMENT_ACCESSORY [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude! The police station's next door![n][f 0 4][e]

[msg ACCESSORY_SHOP_CLOSE]
[f 0 8 65278][f 1 31]> The lights are off.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's closed.[n][f 0 4][e]

[msg GO_INTO_CLUB [Fuuka]]
[f 0 8 65278][f 1 31][f 0 31 6 12 1 1]Are you ready?[n][f 0 4][e]

[msg HUKA_LETS_GO [Fuuka]]
[f 0 8 65278][f 1 31][f 0 31 6 12 1 1]Good luck.[n][f 0 4][e]

[msg CLUB_STOP [Fuuka]]
[f 0 8 65278][f 1 31][f 0 31 6 12 1 1]It's too dangerous without a full[n]party...[n][f 0 4][e]

[msg CLUB_NOT_OPEN]
[f 0 8 65278][f 1 31]> It's not open yet.[n][f 0 4][e]

[msg JUNPEI_COMMENT_CLUB [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, this place doesn't open until[n]later...[n][f 0 4][e]

[sel BOSS_SEL top]
[f 0 8 65278][f 1 31]"Let's go."[e]
[f 0 8 65278][f 1 31]"Hold on."[e]

[msg JUNPEI_STOP_DRUGSTORE [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Let's go to the police station first,[n]man...[n][f 0 4][e]

[msg INTO_POLICEBOX_OK]
[f 0 8 65278][f 1 31]> This seems to be the police station.[n][f 0 4][e]

[msg POLICEMAN_NOT_HERE]
[f 0 8 65278][f 1 31]> No one is here; Officer Kurosawa[n]must be on patrol...[n][f 0 4][e]

[msg COFFEE_TEIKYU]
[f 0 8 65278][f 1 31]> Chagall Cafe...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg COFFEE_ANNOUNCE]
[f 0 8 65278][f 1 31]> Chagall Cafe...[n][f 0 4][e]

[msg COFFEE_MENU [Menu]]
[f 0 8 65278][f 1 31]"Pheromone Coffee - 500 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"A charming flavor that will turn on[n]your charm."[n][f 0 4][e]

[msg MIRYOKU_MAX_NG]
[f 0 8 65278][f 1 31]> It seems your Charm may not get any[n]higher.[n][f 0 4][e]

[msg HAIRU_SINYA]
[f 0 8 65278][f 1 31]> Will you stay here until midnight?[n][f 0 4][e]

[msg HAIRU_YORU]
[f 0 8 65278][f 1 31]> Will you stay here until it gets[n]dark?[n][f 0 4][e]

[sel YESNO_SEL top]
[f 0 8 65278][f 1 31]Yes[e]
[f 0 8 65278][f 1 31]No[e]

[msg MONEY_TARINAI]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You didn't have enough money.[n][f 0 4][e]

[sel INTO_SEL top]
[f 0 8 65278][f 1 31]Enter[e]
[f 0 8 65278][f 1 31]Don't enter[e]

[msg JIKANTUBUSI_TUTO]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]Here, you can spend time in shops[n]such as these.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Depending on where you go, you may[n]be able to raise your Charm, Courage,[n]or Academics.[n][f 0 4][e]
[f 0 8 65278][f 1 31]If these stats are high enough,[n]then you may even be able to make[n]new acquaintances.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Beyond that, you can also raise your[n]Persona's stats at the arcade.[n][e]

[msg KARAOKE_NG]
[f 0 8 65278][f 1 31]> The worker seems really busy.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15]Worker[n]I'm terribly sorry, but we're full at[n]the moment.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Weekends are always like this,[n]so you may want to try some other[n]time.[n][f 0 4][e]

[msg KARAOKE_ANNOUNCE]
[f 0 8 65278][f 1 31]> Mandragora...[n][f 0 4][e]

[msg KARAOKE_MENU [Menu]]
[f 0 8 65278][f 1 31]"Karaoke Solo - 800 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"Don't be shy... Belt it out!"[n][f 0 4][e]

[msg YUUKI_MAX_NG]
[f 0 8 65278][f 1 31]> It seems your Courage may not get[n]any higher.[n][f 0 4][e]

[msg KARAOKE_CONTINUE]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]

[msg KARAOKE_END]
[f 0 8 65278][f 1 31]> You sang for hours and hours.[n][f 0 4][e]

[msg PARAM_RANK_UP_YUUKI]
[f 0 8 65278][f 1 31]> Your Courage has changed from[n][f 0 3 0] to [f 0 3 1]![n][f 0 4][e]

[msg RYOU_KAERU_SINYA]
[f 0 8 65278][f 1 31]> It's getting late.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You decide to go back to the dorm.[n][f 0 4][e]

[msg RYOU_KAERU]
[f 0 8 65278][f 1 31]> It's getting late.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You decide to go back to the dorm.[n][f 0 4][e]

[msg YUUKI_UP]
[f 0 8 65278][f 1 31]> Your Courage has increased.[n][f 0 4][e]

[msg KOTTOU_NG]
[f 0 8 65278][f 1 31]> It's an antique store.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> However, it seems to be closed.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> The sign says it will reopen on[n]June 9th.[n][f 0 4][e]

[msg JUNPEI_COMMENT_ANTIQUE [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Oh, it's not open, huh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]...Wait a minute! This isn't the[n]police station![n][f 0 4][e]

[msg JUNPEI_STOP_COFFEE [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]You wanna have a cup of tea?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Well, too bad! We gotta go to the[n]police station![n][f 0 4][e]

[msg JUNPEI_STOP_KARAOKE [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, we can check it out AFTER[n]we go to the police station.[n][f 0 4][e]
[f 0 8 65278][f 1 31]But, there's no way I'm doing a duet[n]with you![n][f 0 4][e]

[msg STOP_UFO_CATCHER]
[f 0 8 65278][f 1 31]> It seems like the electricity is out.[n][f 0 4][e]

[msg UFO_CATHER_02]
[f 0 8 65278][f 1 31]> It's a crane game.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> One of the prizes is a [f 0 29 4095].[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It costs 200 yen to play. Will you[n]give it a try?[n][f 0 4][e]

[msg UFO_CATHER]
[f 0 8 65278][f 1 31]> It's a crane game.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> One of the prizes is a [f 0 29 4092].[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It costs 200 yen to play. Will you[n]give it a try?[n][f 0 4][e]

[msg UFO_CATHER_CONTINUE]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]

[msg UFO_CATHER_GET]
[f 0 8 65278][f 1 31]> You won![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 16 4092 1]> Obtained [f 0 29 4092]![n][f 0 4][e]

[msg UFO_CATHER_GET_02]
[f 0 8 65278][f 1 31]> You won![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 16 4095 1]> Obtained [f 0 29 4095]![n][f 0 4][e]

[msg UFO_CATHER_NG]
[f 0 8 65278][f 1 31]> The crane grabbed nothing but air.[n][f 0 4][e]

[msg JUNPEI_STOP_GAME [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Alright, alright! But, after the[n]police station, okay!?[n][f 0 4][e]

[msg GAMEC_SETUMEI]
[f 0 8 65278][f 1 31]> Game Panic...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Various arcade games are inside.[n][f 0 4][e]

[msg GAMEC_CHOICE]
[f 0 8 65278][f 1 31]> Right now, the games available[n]to play are...[n][f 0 4][e]

[sel GAMEC_CHOICE_SEL01 top]
[f 0 8 65278][f 1 31]Print Club - 1,500 yen[e]
[f 0 8 65278][f 1 31]Punching Bag - 2,000 yen[e]
[f 0 8 65278][f 1 31]Leave[e]

[sel GAMEC_CHOICE_SEL02 top]
[f 0 8 65278][f 1 31]Horror House - 3,000 yen[e]
[f 0 8 65278][f 1 31]Mole Whackers - 2,000 yen[e]
[f 0 8 65278][f 1 31]Leave[e]

[sel GAMEC_CHOICE_SEL03 top]
[f 0 8 65278][f 1 31]Quiz Game - 3,000 yen[e]
[f 0 8 65278][f 1 31]Lucky Fortune - 2,000 yen[e]
[f 0 8 65278][f 1 31]Leave[e]

[sel GAMEC_CHOICE_SEL04 top]
[f 0 8 65278][f 1 31]Punching Bag - 2,000 yen[e]
[f 0 8 65278][f 1 31]Mole Whackers - 2,000 yen[e]
[f 0 8 65278][f 1 31]Lucky Fortune - 2,000 yen[e]
[f 0 8 65278][f 1 31]Leave[e]

[msg GAMEC_END_01]
[f 0 8 65278][f 1 31]> You tested your mastery of trivia[n]against players from all over Japan...[n][f 0 4][e]

[msg GAKURYOKU_UP]
[f 0 8 65278][f 1 31]> Your Academics have increased![n][f 0 4][e]

[msg PARAM_RANK_UP_GAKURYOKU]
[f 0 8 65278][f 1 31]> Your Academics changed from[n]"[f 0 3 0]" to "[f 0 3 1]"![n][f 0 4][e]

[msg GAMEC_END_02]
[f 0 8 65278][f 1 31]> You showed the machine what you[n]could dish out.[n][f 0 4][e]

[msg TIKARA_UP]
[f 0 8 65278][f 1 31]> Your Persona's Strength has[n]increased![n][f 0 4][e]

[msg GAMEC_END_03]
[f 0 8 65278][f 1 31]> You whacked as many of the wily[n]moles as you could...[n][f 0 4][e]

[msg SOKU_UP]
[f 0 8 65278][f 1 31]> Your Persona's Speed has[n]increased![n][f 0 4][e]

[msg GAMEC_END_04]
[f 0 8 65278][f 1 31]> Dr. Edgar's macabre fortune nearly[n]came true...[n][f 0 4][e]

[msg MARYOKU_UP]
[f 0 8 65278][f 1 31]> Your Persona's Magic has[n]increased![n][f 0 4][e]

[msg GAMEC_END_05]
[f 0 8 65278][f 1 31]> You watched a scary video in the[n]small, enclosed booth...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You were alone inside, but it[n]somehow felt like there was someone[n]else with you...[n][f 0 4][e]

[msg GAMEC_END_06]
[f 0 8 65278][f 1 31]> Your photo came out fantastically![n][f 0 4][e]
[f 0 8 65278][f 1 31]> You tried out different poses and[n]graphics...[n][f 0 4][e]

[msg MIRYOKU_UP]
[f 0 8 65278][f 1 31]> Your Charm has increased.[n][f 0 4][e]

[msg PARAM_RANK_UP_MIRYOKU]
[f 0 8 65278][f 1 31]> Your Charm changed from[n]"[f 0 3 0]" to "[f 0 3 1]"![n][f 0 4][e]

[msg PARAM_MAX_SUMI]
[f 0 8 65278][f 1 31]> But it seems that statistic[n]can't go any higher...[n][f 0 4][e]

[msg GOTO_TEACHERS_ROOM]
[f 0 8 65278][f 1 31]> You should go to the office.[n][f 0 4][e]

[msg STOP_EXIT [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]What are you doing? We just came in![n][f 0 4][e]

[msg STOP_UPSTAIR [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]Hey, wrong way![n][f 0 4][e]

[msg STOP_INTO_SCHOOL [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]...Hey! We've gotta get to the police[n]station![n][f 0 4][e]

[msg STOP_TO_ROOFTOP [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]*sigh* Can we look for the keys,[n]already?[n][f 0 4][e]

[msg STOP_TO_ROUNDABOUT_WAY [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]The others will search that way.[n][f 0 4][e]
[f 0 8 65278][f 1 31]We're s'posed to go to the office,[n]remember?[n][f 0 4][e]

[msg STOP_ENTRANCE [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]Let's get this over with, alright?[n]It's creepy in here![n][f 0 4][e]

[msg ROOM_STOP_01 [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 4 1]We could hide in this room...[n][f 0 4][e]
[f 0 8 65278][f 1 31]N-No...[n][f 0 4][e]
[f 0 8 65278][f 1 31]That wouldn't work after all...[n][f 0 4][e]

[msg STOP_GO_OUT_YUKARI [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 1 1 1]You're not allowed to go out,[n]since it's past curfew.[n][f 0 4][e]

[msg STOP_GO_OUT_MITSURU [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 1 1 1]We cannot allow you to go out[n]after dark.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Sorry, but rules are rules.[n][f 0 4][e]

[msg STOP_GO_OUT]
[f 0 8 65278][f 1 31]> You aren't allowed to go outside[n]at nighttime.[n][f 0 4][e]

[msg STOP_GO_OUT_MITSURU_0419 [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 1 1 1]Have you finished your homework?[n][f 0 4][e]

[msg STORM_COMING]
[f 0 8 65278][f 1 31]> It's raining outside...[n][f 0 4][e]

[msg STORM_COMING_JUNPEI [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Hey! Where do you think you're[n]going, man?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Forget about it! You're gonna[n]catch a cold, dude.[n][f 0 4][e]

[msg GO_OUT_OK]
[f 0 8 65278][f 1 31]> Will you go out until dark?[n][f 0 4][e]

[msg GO_OUT_OK_HELP]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]If you go outside, when you come[n]back to the dorm, it will become[n]nighttime.[n][f 0 4][e]

[sel GOOUT_SEL top]
[f 0 8 65278][f 1 31]Go out[e]
[f 0 8 65278][f 1 31]Don't go out[e]

[msg YUKARI_STOP_2F_DWNSTAIR [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 4 1]Y-You can't go down there![n][f 0 4][e]
[f 0 8 65278][f 1 31]I'm sure they have it under[n]control...[n][f 0 4][e]

[msg SANADA_CALLING [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]You didn't forget about going to[n]the police station, right?[n][f 0 4][e]

[msg GOINTO_HOME]
[f 0 8 65278][f 1 31]> It's almost nighttime...[n][f 0 4][e]

[msg HELP_GOINTO_HOME]
[f 0 8 65278][f 1 31][f 2 2 65535 65535][f 2 3 65535 0]If you go back into the dorm,[n]then it will automatically become[n]nighttime.[n][f 0 4][e]

[msg GOINTO_HOME_OK]
[f 0 8 65278][f 1 31]> Will you go back to the dorm now?[n][f 0 4][e]

[sel INTO_HOME_SEL top]
[f 0 8 65278][f 1 31]Go back to the dorm[e]
[f 0 8 65278][f 1 31]Don't go back yet[e]

[msg OUTDOOR_MYROOM]
[f 0 8 65278][f 1 31]> You should rest for today, and[n]do that tomorrow.[n][f 0 4][e]

[msg YUKARI_STOP_UP [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 4 1]I don't want to go downstairs![n][f 0 4][e]
[f 0 8 65278][f 1 31]I-I mean... We can't...[n][f 0 4][e]

[msg OPERATION_ROOM_STOP]
[f 0 8 65278][f 1 31]> The door is locked.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> What's in this room...?[n][f 0 4][e]

[msg OUT_STOP [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]If you waste any more time,[n]the Dark Hour will fade away.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Prepare to infiltrate Escapade![n][f 0 4][e]

[msg JUNPEI_STOP_ALLEY [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, you passed the police station![n][f 0 4][e]
[f 0 8 65278][f 1 31]Turn left![n][f 0 4][e]

[sel MSG_NPC000_SEL1 top]
[f 0 8 65278][f 1 31]Rose Bouquet[e]
[f 0 8 65278][f 1 31]Red Pine Bonsai[e]
[f 0 8 65278][f 1 31]Look at the other flowers[e]
[f 0 8 65278][f 1 31]Never mind[e]

[sel MSG_NPC000_SEL2 top]
[f 0 8 65278][f 1 31]Mini Cactus[e]
[f 0 8 65278][f 1 31]Glass Vase[e]
[f 0 8 65278][f 1 31]Look at the other flowers[e]
[f 0 8 65278][f 1 31]Never mind[e]

[msg MSG_NPC000_FST [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Welcome to Rafflesia.[n][f 0 4][e]
[f 0 8 65278][f 1 31]What kind of flowers are you[n]looking for today?[n][f 0 4][e]

[msg MSG_NPC000_FST2 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Would you like another type[n]of flower?[n][f 0 4][e]

[msg MSG_NPC000_FLOWER1 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]It'll be 2,000 yen for[n][f 0 25 0].[n][f 0 4][e]

[msg MSG_NPC000_FLOWER2 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]It'll be 3,000 yen for[n][f 0 25 0].[n][f 0 4][e]

[msg MSG_NPC000_FLOWER3 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]It'll be 4,000 yen for[n][f 0 25 0].[n][f 0 4][e]

[msg MSG_NPC000_FLOWER4 [Flower Shop Lady]]
[f 0 8 65278][f 1 31]It'll be 5,000 yen for[n][f 0 25 0].[n][f 0 4][e]

[sel MSG_NPC000_YESNO top]
[f 0 8 65278][f 1 31]"Sure."[e]
[f 0 8 65278][f 1 31]"On second thought..."[e]

[msg MSG_NPC000_THANKS [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Thank you very much for[n]your purchase.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Obtained [f 0 25 0].[n][f 1 17][e]

[msg MSG_NPC000_BYE [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Please come again.[n][f 0 4][e]

[msg MSG_NPC000_DONTHAVE [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Hmm? You don't have enough space[n]for [f 0 25 0].[n][f 0 4][e]
[f 0 8 65278][f 1 31]Come back once you've organized[n]your belongings.[n][f 0 4][e]

[msg MSG_NPC000_NOMONEY [Flower Shop Lady]]
[f 0 8 65278][f 1 31]Hmm? You don't have enough money.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Save up, and come back again.[n][f 0 4][e]

[msg JUNPEI_STOP_THEATER [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, that's NOT the police station...[n][f 0 4][e]

[msg MOVIE_TEIKYU]
[f 0 8 65278][f 1 31]> Screen Shot Movie Theater...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Tickets are sold out.[n][f 0 4][e]

[msg MOVIE_THEATER]
[f 0 8 65278][f 1 31]> Screen Shot Movie Theater...[n][f 0 4][e]

[msg MOVIE_PROGRAM_01]
[f 0 8 65278][f 1 31]> A movie marathon is playing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "For those of you who want to be[n]more charming, two French films are[n]being shown."[n][f 0 4][e]

[msg MOVIE_PROGRAM_02]
[f 0 8 65278][f 1 31]> A movie marathon is playing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "For those of you who want to be[n]more courageous, three heroic tales[n]are being shown."[n][f 0 4][e]

[msg MOVIE_PROGRAM_03]
[f 0 8 65278][f 1 31]> A movie marathon is playing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "For those of you who want to be[n]more charming, check out these epic[n]tales of love."[n][f 0 4][e]

[msg MOVIE_PROGRAM_04]
[f 0 8 65278][f 1 31]> A movie marathon is playing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> "Are you brave enough to endure[n]these tales of terror?"[n][f 0 4][e]

[msg MOVIE_PROGRAM_CONTINUE]
[f 0 8 65278][f 1 31]> A student ticket is 1500 yen.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> Would you like to stay and watch[n]some movies?[n][f 0 4][e]

[msg MOVIE_CONTINUE]
[f 0 8 65278][f 1 31]> ...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> ......[n][f 0 4][e]
[f 0 8 65278][f 1 31]> .........[n][f 0 4][e]

[msg MOVIE_END_01]
[f 0 8 65278][f 1 31]> You have learned some romantic[n]one-liners.[n][f 0 4][e]

[msg MOVIE_END_02]
[f 0 8 65278][f 1 31]> You've been inspired to be more[n]courageous.[n][f 0 4][e]

[msg MOVIE_END_03]
[f 0 8 65278][f 1 31]> You've learned some new ways to[n]catch a girl's eye.[n][f 0 4][e]

[msg MOVIE_END_04]
[f 0 8 65278][f 1 31]> You almost screamed, but you held[n]it in.[n][f 0 4][e]

[msg SHOP_STOP_JUNPEI [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 12 1 1]Dude, hurry up![n][f 0 4][e]

[msg JUNPEI_STOP_BURGER [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, this place is so bad for you,[n]but sometimes I just get a craving.[n][f 0 4][e]
[f 0 8 65278][f 1 31]...Hey, what about Paulownia Mall?[n][f 0 4][e]

[msg BURGER_TEIKYU]
[f 0 8 65278][f 1 31]> Wild-duck Burger...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg BURGER_ANNOUNCE]
[f 0 8 65278][f 1 31]> Wild-duck Burger...[n][f 0 4][e]

[msg BURGER_HAIRU [Menu]]
[f 0 8 65278][f 1 31]"Mystery Burger - 500 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"The ingredients are a secret!"[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15] [n]> You need a little bit of Courage to[n]eat here.[n][f 0 4][e]

[msg BURGER_HAIRU02]
[f 0 8 65278][f 1 31]> Will you stay here until it gets[n]dark?[n][f 0 4][e]

[msg JUNPEI_STOP_RESTAURANT [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Oh yeah, we better eat before we go to[n]the police station, huh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]...Wait a minute! That's not as[n]important![n][f 0 4][e]

[msg WASHOKU_ANNOUNCE]
[f 0 8 65278][f 1 31]> Wakatsu Restaurant...[n][f 0 4][e]

[msg WASHOKU_HAIRU [Menu]]
[f 0 8 65278][f 1 31]"Prodigy Platter - 680 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"Get smarter while you digest!"[n][f 0 4][e]

[msg WASHOKU_HAIRU02]
[f 0 8 65278][f 1 31]> Will you stay here until it gets[n]dark?[n][f 0 4][e]

[msg WASHOKU_TEIKYU]
[f 0 8 65278][f 1 31]> Wakatsu Restaurant...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg JUNPEI_STOP_RAMEN [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]I heard the ramen here kicks ass.[n]Wanna try it?[n][f 0 4][e]
[f 0 8 65278][f 1 31]...Hang on. We gotta get to Paulownia[n]Mall since Akihiko-senpai is waiting.[n][f 0 4][e]

[msg RAMEN_ANNOUNCE]
[f 0 8 65278][f 1 31]> Ramen shop "Hagakure"...[n][f 0 4][e]

[msg RAMEN_HAIRU [Menu]]
[f 0 8 65278][f 1 31]"Tuna - 900 yen"[n][f 0 4][e]
[f 0 8 65278][f 1 31]"The collagen will make your skin[n]beautiful!"[n][f 0 4][e]

[msg RAMEN_HAIRU02]
[f 0 8 65278][f 1 31]> Will you stay here until it gets[n]dark?[n][f 0 4][e]

[msg RAMEN_TEIKYU]
[f 0 8 65278][f 1 31]> Ramen shop "Hagakure"...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg GAKURYOKU_MAX_NG]
[f 0 8 65278][f 1 31]> You don't need to increase your[n]Academics.[n][f 0 4][e]

[msg JUNPEI_STOP_BEEF [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Are you dumb or what? How many times[n]do I have to tell you...?[n][f 0 4][e]
[f 0 8 65278][f 1 31]WE GOTTA GET TO THE[n]POLICE STATION![n][f 0 4][e]

[msg GYUDON_SETUMEI]
[f 0 8 65278][f 1 31]> Beef Bowl Shop...[n][f 0 4][e]
[f 0 8 65278][f 1 31]> It's too crowded right now.[n][f 0 4][e]

[msg STATION_STOP [Fuuka]]
[f 0 8 65278][f 1 31][f 0 31 6 12 1 1]You need more people in your party...[n]This is serious.[n][f 0 4][e]

[msg GOTO_STATION [Fuuka]]
[f 0 8 65278][f 1 31][f 0 31 6 12 1 1]Are you ready?[n][f 0 4][e]