[msg Record_Closed]
[f 0 8 65278][f 1 31]> It's a record store.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> However, it seems to be closed.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> The sign says it will reopen on[n]June 11th.[n][f 0 4][e]

[msg Closed_Day]
[f 0 8 65278][f 1 31]> The worker seems really busy.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15]Worker[n]I'm terribly sorry, but we're full at[n]the moment.[n][f 0 4][e]
[f 0 8 65278][f 1 31]We are extra busy because we just reopened.[n]You may want to try coming back tonight.[n][f 0 4][e]

[msg Shop_Greeting [Power Records Worker]]
[f 0 8 65278][f 1 31]Welcome to Power Records.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Everything is 2000 Yen.[n][f 0 4][e]
[f 0 8 65278][f 1 31]What kind of music are you[n]looking for today?[n][f 0 4][e]

[msg Shop_Greeting2 [Power Records Worker]]
[f 0 8 65278][f 1 31]What kind of music are you[n]looking for today?[n][f 0 4][e]

[msg Shop_Choose_Series]
[f 0 8 -258][f 1 31]> What series would you like to shop for?[e]

[msg ShopChoose1of1 [Page 1 of 1]]
[f 0 8 -258][f 1 31]> What album would you like?[e]

[msg ShopChoose1of2 [Page 1 of 2]]
[f 0 8 -258][f 1 31]> What album would you like?[e]

[msg ShopChoose2of2 [Page 2 of 2]]
[f 0 8 -258][f 1 31]> What album would you like?[e]

[msg Already_Own]
[f 0 8 65278][f 1 31]> You already own this album.[n][f 0 4][e]

[msg Broke [Power Records Worker]]
[f 0 8 65278][f 1 31]Hey! You don't have enough money.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Come back after you've made some cash.[n][f 0 4][e]

[msg Thanks [Power Records Worker]]
[f 0 8 65278][f 1 31]Thank you for your purchase.[n][f 0 4][e]

[msg KeepShopping [Power Records Worker]]
[f 0 8 65278][f 1 31]Would you like anything else?[n][f 0 4][e]

[sel ShopAgain]
[f 0 8 -258][f 1 31]Yes[e]
[f 0 8 -258][f 1 31]No[e]

[sel Record]
[f 0 8 -258][f 1 31]Persona[e]
[f 0 8 -258][f 1 31]SMT[e]
[f 0 8 -258][f 1 31]SMT Spin-Offs[e]

[sel PersonaShop1]
[f 0 8 -258][f 1 31]Persona 1 Soundtrack[e]
[f 0 8 -258][f 1 31]Persona 2: Innocent Sin Soundtrack[e]
[f 0 8 -258][f 1 31]Persona 2: Eternal Punishment Soundtrack[e]
[f 0 8 -258][f 1 31]Persona 3 Soundtrack[e]

[sel PersonaShop2]
[f 0 8 -258][f 1 31]Persona 4 Soundtrack[e]
[f 0 8 -258][f 1 31]Persona Q Soundtrack[e]
[f 0 8 -258][f 1 31]Persona 5 Soundtrack[e]

[sel SMTShop]
[f 0 8 -258][f 1 31]SMT 1, 2, & if... Soundtrack[e]
[f 0 8 -258][f 1 31]SMT 3 & 4 Soundtrack[e]

[sel SpinShop1]
[f 0 8 -258][f 1 31]Majin Tensei 1 Soundtrack[e]
[f 0 8 -258][f 1 31]Majin Tensei 2 Soundtrack[e]
[f 0 8 -258][f 1 31]Digital Devil Saga Soundtrack[e]

[sel SpinShop2]
[f 0 8 -258][f 1 31]Raidou 1 & 2 Soundtrack[e]
[f 0 8 -258][f 1 31]Others Soundtrack[e]