[msg Record_Closed]
[f 0 8 65278][f 1 31]> It's a record store.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> However, it seems to be closed.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> The sign says it will reopen on[n]June 11th.[n][f 0 4][e]

[msg Closed_Day]
[f 0 8 65278][f 1 31]> The worker seems really busy.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 15]Worker[n]I'm terribly sorry, but we're full at[n]the moment.[n][f 0 4][e]
[f 0 8 65278][f 1 31]We are extra busy because we just reopened.[n]You may want to try coming back tonight.[n][f 0 4][e]